/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.bosoft.formularios;

import ar.com.bosoft.conexion.ActiveDatabase;
import ar.com.matera.TableModels.TipoOpTableModel;
import javax.swing.JOptionPane;
import matera.db.managers.TipoOpMgr;
import matera.jooq.tables.records.TipooperacionRecord;

/**
 *
 * @author tinchogava
 */
public class ABMTipoOp extends javax.swing.JInternalFrame {
    protected TipoOpTableModel modeloTipoOp;
    /**
     * Creates new form ABMTipoOp
     */
    public ABMTipoOp() {
   
        initComponents();
        
        modeloTipoOp = new TipoOpTableModel();
        modeloTipoOp.getPropertiesFromDefaultModel(jTableOp.getModel());
        jTableOp.setModel(modeloTipoOp);
        TipoOpMgr.getTipoOp().forEach(p->modeloTipoOp.addRow(p));
        
    }
    private boolean validaObligatorios(){
           return !this.jTxtNombre.getText().isEmpty();
       }
 private void limpia(){
        this.jTxtNombre.setText("");
        this.jComboEn.setSelectedItem("SI");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboEn = new javax.swing.JComboBox<>();
        jTxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOp = new javax.swing.JTable();
        jExitButton = new javax.swing.JButton();

        setMaximizable(false);
        setResizable(true);
        setTitle("ABM Tipo de Operacion");

        jLabel1.setText("* Nombre");

        jLabel2.setText("* Habilitado");

        jComboEn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jComboEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEnActionPerformed(evt);
            }
        });

        jTxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("(*)Datos Obligatorios");
        jLabel3.setSize(new java.awt.Dimension(25, 16));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/32x32/rollover/guardar.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorder(null);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/32x32/rollover/guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableOp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "codigo", "nombre", "habilitado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOp);
        if (jTableOp.getColumnModel().getColumnCount() > 0) {
            jTableOp.getColumnModel().getColumn(0).setResizable(false);
            jTableOp.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableOp.getColumnModel().getColumn(2).setResizable(false);
            jTableOp.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/32x32/rollover/salir.png"))); // NOI18N
        jExitButton.setText("Salir");
        jExitButton.setBorder(null);
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(41, 41, 41)
                                .addComponent(jExitButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExitButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (validaObligatorios()){
            TipooperacionRecord tipoOpRecord = new TipooperacionRecord();
            tipoOpRecord.attach(ActiveDatabase.getDSLContext().configuration());
            tipoOpRecord.setIdTipooperacion(null);
            tipoOpRecord.setNombre(jTxtNombre.getText());
            tipoOpRecord.setHabilita(this.jComboEn.getSelectedItem().toString().substring(0, 1));
            
            TipoOpMgr.storeOp(tipoOpRecord);
            
            this.limpia();
            this.jTxtNombre.requestFocus();
        }
         
        modeloTipoOp.getRowsAsList()
                 .forEach(tOp->{
                     if(tOp.changed()){
                         tOp.store();
                     }
                 });
        
        modeloTipoOp.removeAllRows();
        
        TipoOpMgr.getTipoOp()
                .forEach(p->
                        modeloTipoOp.addRow(p)
                );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEnActionPerformed
        // TODO add your handling code
    }//GEN-LAST:event_jComboEnActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
            
        if(validaObligatorios()){
            if(JOptionPane.showOptionDialog(this,
                    "¿Desea salir sin guardar?",
                    "Salir",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[]{" SI "," NO "},
                    "NO")==0)
                {
                    this.dispose();
                }else{
                    JOptionPane.getDefaultLocale();
                    
                }
            }else{
            this.dispose();
        }
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jTableOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOpMouseClicked
             if (evt.getClickCount() == 2) {
                int fila = jTableOp.convertRowIndexToModel(jTableOp.getSelectedRow());
                
             }
    }//GEN-LAST:event_jTableOpMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboEn;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOp;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
