/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.AccesoRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Acceso extends TableImpl<AccesoRecord> {

	private static final long serialVersionUID = -1858740045;

	/**
	 * The reference instance of <code>matera.acceso</code>
	 */
	public static final Acceso ACCESO = new Acceso();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AccesoRecord> getRecordType() {
		return AccesoRecord.class;
	}

	/**
	 * The column <code>matera.acceso.id_acceso</code>.
	 */
	public final TableField<AccesoRecord, UInteger> ID_ACCESO = createField("id_acceso", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>matera.acceso.id_usuario</code>.
	 */
	public final TableField<AccesoRecord, UInteger> ID_USUARIO = createField("id_usuario", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.acceso.id_menu</code>.
	 */
	public final TableField<AccesoRecord, UInteger> ID_MENU = createField("id_menu", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.acceso.id_empresa</code>.
	 */
	public final TableField<AccesoRecord, Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>matera.acceso</code> table reference
	 */
	public Acceso() {
		this("acceso", null);
	}

	/**
	 * Create an aliased <code>matera.acceso</code> table reference
	 */
	public Acceso(String alias) {
		this(alias, ACCESO);
	}

	private Acceso(String alias, Table<AccesoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Acceso(String alias, Table<AccesoRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AccesoRecord, UInteger> getIdentity() {
		return Keys.IDENTITY_ACCESO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AccesoRecord> getPrimaryKey() {
		return Keys.KEY_ACCESO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AccesoRecord>> getKeys() {
		return Arrays.<UniqueKey<AccesoRecord>>asList(Keys.KEY_ACCESO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Acceso as(String alias) {
		return new Acceso(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Acceso rename(String name) {
		return new Acceso(name, null);
	}
}
