/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.CajaasignadaRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cajaasignada extends TableImpl<CajaasignadaRecord> {

	private static final long serialVersionUID = -813867977;

	/**
	 * The reference instance of <code>matera.cajaasignada</code>
	 */
	public static final Cajaasignada CAJAASIGNADA = new Cajaasignada();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CajaasignadaRecord> getRecordType() {
		return CajaasignadaRecord.class;
	}

	/**
	 * The column <code>matera.cajaasignada.id_cajaAsignada</code>.
	 */
	public final TableField<CajaasignadaRecord, Integer> ID_CAJAASIGNADA = createField("id_cajaAsignada", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.cajaasignada.id_presupuesto</code>.
	 */
	public final TableField<CajaasignadaRecord, Integer> ID_PRESUPUESTO = createField("id_presupuesto", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.cajaasignada.id_cajaDeposito</code>.
	 */
	public final TableField<CajaasignadaRecord, Integer> ID_CAJADEPOSITO = createField("id_cajaDeposito", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>matera.cajaasignada</code> table reference
	 */
	public Cajaasignada() {
		this("cajaasignada", null);
	}

	/**
	 * Create an aliased <code>matera.cajaasignada</code> table reference
	 */
	public Cajaasignada(String alias) {
		this(alias, CAJAASIGNADA);
	}

	private Cajaasignada(String alias, Table<CajaasignadaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cajaasignada(String alias, Table<CajaasignadaRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CajaasignadaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CAJAASIGNADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CajaasignadaRecord> getPrimaryKey() {
		return Keys.KEY_CAJAASIGNADA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CajaasignadaRecord>> getKeys() {
		return Arrays.<UniqueKey<CajaasignadaRecord>>asList(Keys.KEY_CAJAASIGNADA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cajaasignada as(String alias) {
		return new Cajaasignada(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cajaasignada rename(String name) {
		return new Cajaasignada(name, null);
	}
}
