/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.CajacomposicionRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cajacomposicion extends TableImpl<CajacomposicionRecord> {

	private static final long serialVersionUID = -1916373209;

	/**
	 * The reference instance of <code>matera.cajacomposicion</code>
	 */
	public static final Cajacomposicion CAJACOMPOSICION = new Cajacomposicion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CajacomposicionRecord> getRecordType() {
		return CajacomposicionRecord.class;
	}

	/**
	 * The column <code>matera.cajacomposicion.id_cajaComposicion</code>.
	 */
	public final TableField<CajacomposicionRecord, Integer> ID_CAJACOMPOSICION = createField("id_cajaComposicion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.cajacomposicion.id_cajaDeposito</code>.
	 */
	public final TableField<CajacomposicionRecord, Integer> ID_CAJADEPOSITO = createField("id_cajaDeposito", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.cajacomposicion.id_producto</code>.
	 */
	public final TableField<CajacomposicionRecord, Integer> ID_PRODUCTO = createField("id_producto", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.cajacomposicion.cantidad</code>.
	 */
	public final TableField<CajacomposicionRecord, Integer> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.cajacomposicion.usuario</code>.
	 */
	public final TableField<CajacomposicionRecord, String> USUARIO = createField("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.cajacomposicion.fechaReal</code>.
	 */
	public final TableField<CajacomposicionRecord, Timestamp> FECHAREAL = createField("fechaReal", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>matera.cajacomposicion</code> table reference
	 */
	public Cajacomposicion() {
		this("cajacomposicion", null);
	}

	/**
	 * Create an aliased <code>matera.cajacomposicion</code> table reference
	 */
	public Cajacomposicion(String alias) {
		this(alias, CAJACOMPOSICION);
	}

	private Cajacomposicion(String alias, Table<CajacomposicionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cajacomposicion(String alias, Table<CajacomposicionRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CajacomposicionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CAJACOMPOSICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CajacomposicionRecord> getPrimaryKey() {
		return Keys.KEY_CAJACOMPOSICION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CajacomposicionRecord>> getKeys() {
		return Arrays.<UniqueKey<CajacomposicionRecord>>asList(Keys.KEY_CAJACOMPOSICION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cajacomposicion as(String alias) {
		return new Cajacomposicion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cajacomposicion rename(String name) {
		return new Cajacomposicion(name, null);
	}
}
