/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.ClasientidadRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clasientidad extends TableImpl<ClasientidadRecord> {

	private static final long serialVersionUID = 1482418529;

	/**
	 * The reference instance of <code>matera.clasientidad</code>
	 */
	public static final Clasientidad CLASIENTIDAD = new Clasientidad();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ClasientidadRecord> getRecordType() {
		return ClasientidadRecord.class;
	}

	/**
	 * The column <code>matera.clasientidad.id_clasiEntidad</code>.
	 */
	public final TableField<ClasientidadRecord, Integer> ID_CLASIENTIDAD = createField("id_clasiEntidad", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.clasientidad.nombre</code>.
	 */
	public final TableField<ClasientidadRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.clasientidad.habilita</code>.
	 */
	public final TableField<ClasientidadRecord, String> HABILITA = createField("habilita", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>matera.clasientidad</code> table reference
	 */
	public Clasientidad() {
		this("clasientidad", null);
	}

	/**
	 * Create an aliased <code>matera.clasientidad</code> table reference
	 */
	public Clasientidad(String alias) {
		this(alias, CLASIENTIDAD);
	}

	private Clasientidad(String alias, Table<ClasientidadRecord> aliased) {
		this(alias, aliased, null);
	}

	private Clasientidad(String alias, Table<ClasientidadRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ClasientidadRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CLASIENTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ClasientidadRecord> getPrimaryKey() {
		return Keys.KEY_CLASIENTIDAD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ClasientidadRecord>> getKeys() {
		return Arrays.<UniqueKey<ClasientidadRecord>>asList(Keys.KEY_CLASIENTIDAD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Clasientidad as(String alias) {
		return new Clasientidad(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Clasientidad rename(String name) {
		return new Clasientidad(name, null);
	}
}
