/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.CotizacionRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cotizacion extends TableImpl<CotizacionRecord> {

	private static final long serialVersionUID = 705353317;

	/**
	 * The reference instance of <code>matera.cotizacion</code>
	 */
	public static final Cotizacion COTIZACION = new Cotizacion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CotizacionRecord> getRecordType() {
		return CotizacionRecord.class;
	}

	/**
	 * The column <code>matera.cotizacion.id_cotizacion</code>.
	 */
	public final TableField<CotizacionRecord, Integer> ID_COTIZACION = createField("id_cotizacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.cotizacion.id_moneda</code>.
	 */
	public final TableField<CotizacionRecord, Integer> ID_MONEDA = createField("id_moneda", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.cotizacion.mes</code>.
	 */
	public final TableField<CotizacionRecord, Integer> MES = createField("mes", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.cotizacion.año</code>.
	 */
	public final TableField<CotizacionRecord, Integer> AÑO = createField("año", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.cotizacion.valor</code>.
	 */
	public final TableField<CotizacionRecord, BigDecimal> VALOR = createField("valor", org.jooq.impl.SQLDataType.DECIMAL.precision(12, 3), this, "");

	/**
	 * The column <code>matera.cotizacion.id_empresa</code>.
	 */
	public final TableField<CotizacionRecord, Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.cotizacion.usuario</code>.
	 */
	public final TableField<CotizacionRecord, String> USUARIO = createField("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>matera.cotizacion.fechaReal</code>.
	 */
	public final TableField<CotizacionRecord, Timestamp> FECHAREAL = createField("fechaReal", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>matera.cotizacion</code> table reference
	 */
	public Cotizacion() {
		this("cotizacion", null);
	}

	/**
	 * Create an aliased <code>matera.cotizacion</code> table reference
	 */
	public Cotizacion(String alias) {
		this(alias, COTIZACION);
	}

	private Cotizacion(String alias, Table<CotizacionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cotizacion(String alias, Table<CotizacionRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CotizacionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_COTIZACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CotizacionRecord> getPrimaryKey() {
		return Keys.KEY_COTIZACION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CotizacionRecord>> getKeys() {
		return Arrays.<UniqueKey<CotizacionRecord>>asList(Keys.KEY_COTIZACION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cotizacion as(String alias) {
		return new Cotizacion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cotizacion rename(String name) {
		return new Cotizacion(name, null);
	}
}
