/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.DiariaRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diaria extends TableImpl<DiariaRecord> {

	private static final long serialVersionUID = -316867769;

	/**
	 * The reference instance of <code>matera.diaria</code>
	 */
	public static final Diaria DIARIA = new Diaria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DiariaRecord> getRecordType() {
		return DiariaRecord.class;
	}

	/**
	 * The column <code>matera.diaria.id_diaria</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_DIARIA = createField("id_diaria", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.diaria.nombre</code>.
	 */
	public final TableField<DiariaRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.direccion</code>.
	 */
	public final TableField<DiariaRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_provincia</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_PROVINCIA = createField("id_provincia", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_departamento</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_DEPARTAMENTO = createField("id_departamento", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_localidad</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_LOCALIDAD = createField("id_localidad", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.codPostal</code>.
	 */
	public final TableField<DiariaRecord, String> CODPOSTAL = createField("codPostal", org.jooq.impl.SQLDataType.VARCHAR.length(6).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_opcion</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_OPCION = createField("id_opcion", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.cuit</code>.
	 */
	public final TableField<DiariaRecord, String> CUIT = createField("cuit", org.jooq.impl.SQLDataType.VARCHAR.length(11).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.telefono1</code>.
	 */
	public final TableField<DiariaRecord, String> TELEFONO1 = createField("telefono1", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.telefono2</code>.
	 */
	public final TableField<DiariaRecord, String> TELEFONO2 = createField("telefono2", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.telefono3</code>.
	 */
	public final TableField<DiariaRecord, String> TELEFONO3 = createField("telefono3", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.telefono4</code>.
	 */
	public final TableField<DiariaRecord, String> TELEFONO4 = createField("telefono4", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.email</code>.
	 */
	public final TableField<DiariaRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.secretaria</code>.
	 */
	public final TableField<DiariaRecord, String> SECRETARIA = createField("secretaria", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.contacto</code>.
	 */
	public final TableField<DiariaRecord, String> CONTACTO = createField("contacto", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.telContacto</code>.
	 */
	public final TableField<DiariaRecord, String> TELCONTACTO = createField("telContacto", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.movContacto</code>.
	 */
	public final TableField<DiariaRecord, String> MOVCONTACTO = createField("movContacto", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.emailContacto</code>.
	 */
	public final TableField<DiariaRecord, String> EMAILCONTACTO = createField("emailContacto", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_zona</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_ZONA = createField("id_zona", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_formaPago</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_FORMAPAGO = createField("id_formaPago", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.observaciones</code>.
	 */
	public final TableField<DiariaRecord, String> OBSERVACIONES = createField("observaciones", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.habilita</code>.
	 */
	public final TableField<DiariaRecord, String> HABILITA = createField("habilita", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaulted(true), this, "");

	/**
	 * The column <code>matera.diaria.id_empresa</code>.
	 */
	public final TableField<DiariaRecord, Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>matera.diaria</code> table reference
	 */
	public Diaria() {
		this("diaria", null);
	}

	/**
	 * Create an aliased <code>matera.diaria</code> table reference
	 */
	public Diaria(String alias) {
		this(alias, DIARIA);
	}

	private Diaria(String alias, Table<DiariaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Diaria(String alias, Table<DiariaRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<DiariaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_DIARIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DiariaRecord> getPrimaryKey() {
		return Keys.KEY_DIARIA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DiariaRecord>> getKeys() {
		return Arrays.<UniqueKey<DiariaRecord>>asList(Keys.KEY_DIARIA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Diaria as(String alias) {
		return new Diaria(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Diaria rename(String name) {
		return new Diaria(name, null);
	}
}
