/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.EncargadocomprasRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Encargadocompras extends TableImpl<EncargadocomprasRecord> {

	private static final long serialVersionUID = 236544482;

	/**
	 * The reference instance of <code>matera.encargadocompras</code>
	 */
	public static final Encargadocompras ENCARGADOCOMPRAS = new Encargadocompras();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EncargadocomprasRecord> getRecordType() {
		return EncargadocomprasRecord.class;
	}

	/**
	 * The column <code>matera.encargadocompras.id_encargadoCompras</code>.
	 */
	public final TableField<EncargadocomprasRecord, Integer> ID_ENCARGADOCOMPRAS = createField("id_encargadoCompras", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.encargadocompras.id_entidad</code>.
	 */
	public final TableField<EncargadocomprasRecord, Integer> ID_ENTIDAD = createField("id_entidad", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocompras.nombre</code>.
	 */
	public final TableField<EncargadocomprasRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocompras.telefono</code>.
	 */
	public final TableField<EncargadocomprasRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocompras.email</code>.
	 */
	public final TableField<EncargadocomprasRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * Create a <code>matera.encargadocompras</code> table reference
	 */
	public Encargadocompras() {
		this("encargadocompras", null);
	}

	/**
	 * Create an aliased <code>matera.encargadocompras</code> table reference
	 */
	public Encargadocompras(String alias) {
		this(alias, ENCARGADOCOMPRAS);
	}

	private Encargadocompras(String alias, Table<EncargadocomprasRecord> aliased) {
		this(alias, aliased, null);
	}

	private Encargadocompras(String alias, Table<EncargadocomprasRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EncargadocomprasRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ENCARGADOCOMPRAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EncargadocomprasRecord> getPrimaryKey() {
		return Keys.KEY_ENCARGADOCOMPRAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EncargadocomprasRecord>> getKeys() {
		return Arrays.<UniqueKey<EncargadocomprasRecord>>asList(Keys.KEY_ENCARGADOCOMPRAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Encargadocompras as(String alias) {
		return new Encargadocompras(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Encargadocompras rename(String name) {
		return new Encargadocompras(name, null);
	}
}
