/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.EncargadocontableRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Encargadocontable extends TableImpl<EncargadocontableRecord> {

	private static final long serialVersionUID = 1865010963;

	/**
	 * The reference instance of <code>matera.encargadocontable</code>
	 */
	public static final Encargadocontable ENCARGADOCONTABLE = new Encargadocontable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EncargadocontableRecord> getRecordType() {
		return EncargadocontableRecord.class;
	}

	/**
	 * The column <code>matera.encargadocontable.id_encargadoContable</code>.
	 */
	public final TableField<EncargadocontableRecord, Integer> ID_ENCARGADOCONTABLE = createField("id_encargadoContable", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.encargadocontable.id_entidad</code>.
	 */
	public final TableField<EncargadocontableRecord, Integer> ID_ENTIDAD = createField("id_entidad", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocontable.nombre</code>.
	 */
	public final TableField<EncargadocontableRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocontable.telefono</code>.
	 */
	public final TableField<EncargadocontableRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.encargadocontable.email</code>.
	 */
	public final TableField<EncargadocontableRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * Create a <code>matera.encargadocontable</code> table reference
	 */
	public Encargadocontable() {
		this("encargadocontable", null);
	}

	/**
	 * Create an aliased <code>matera.encargadocontable</code> table reference
	 */
	public Encargadocontable(String alias) {
		this(alias, ENCARGADOCONTABLE);
	}

	private Encargadocontable(String alias, Table<EncargadocontableRecord> aliased) {
		this(alias, aliased, null);
	}

	private Encargadocontable(String alias, Table<EncargadocontableRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EncargadocontableRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ENCARGADOCONTABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EncargadocontableRecord> getPrimaryKey() {
		return Keys.KEY_ENCARGADOCONTABLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EncargadocontableRecord>> getKeys() {
		return Arrays.<UniqueKey<EncargadocontableRecord>>asList(Keys.KEY_ENCARGADOCONTABLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Encargadocontable as(String alias) {
		return new Encargadocontable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Encargadocontable rename(String name) {
		return new Encargadocontable(name, null);
	}
}
