/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.ForecastentidadRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Forecastentidad extends TableImpl<ForecastentidadRecord> {

	private static final long serialVersionUID = 580602509;

	/**
	 * The reference instance of <code>matera.forecastentidad</code>
	 */
	public static final Forecastentidad FORECASTENTIDAD = new Forecastentidad();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ForecastentidadRecord> getRecordType() {
		return ForecastentidadRecord.class;
	}

	/**
	 * The column <code>matera.forecastentidad.id_forecastEntidad</code>.
	 */
	public final TableField<ForecastentidadRecord, Integer> ID_FORECASTENTIDAD = createField("id_forecastEntidad", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.forecastentidad.id_entidad</code>.
	 */
	public final TableField<ForecastentidadRecord, Integer> ID_ENTIDAD = createField("id_entidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.forecastentidad.id_empresa</code>.
	 */
	public final TableField<ForecastentidadRecord, Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>matera.forecastentidad</code> table reference
	 */
	public Forecastentidad() {
		this("forecastentidad", null);
	}

	/**
	 * Create an aliased <code>matera.forecastentidad</code> table reference
	 */
	public Forecastentidad(String alias) {
		this(alias, FORECASTENTIDAD);
	}

	private Forecastentidad(String alias, Table<ForecastentidadRecord> aliased) {
		this(alias, aliased, null);
	}

	private Forecastentidad(String alias, Table<ForecastentidadRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ForecastentidadRecord, Integer> getIdentity() {
		return Keys.IDENTITY_FORECASTENTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ForecastentidadRecord> getPrimaryKey() {
		return Keys.KEY_FORECASTENTIDAD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ForecastentidadRecord>> getKeys() {
		return Arrays.<UniqueKey<ForecastentidadRecord>>asList(Keys.KEY_FORECASTENTIDAD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Forecastentidad as(String alias) {
		return new Forecastentidad(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Forecastentidad rename(String name) {
		return new Forecastentidad(name, null);
	}
}
