/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.PresupuestoRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Presupuesto extends TableImpl<PresupuestoRecord> {

	private static final long serialVersionUID = 1872804275;

	/**
	 * The reference instance of <code>matera.presupuesto</code>
	 */
	public static final Presupuesto PRESUPUESTO = new Presupuesto();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PresupuestoRecord> getRecordType() {
		return PresupuestoRecord.class;
	}

	/**
	 * The column <code>matera.presupuesto.id_presupuesto</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PRESUPUESTO = createField("id_presupuesto", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.presupuesto.estado</code>. A: Aprobado; R: Rechazado; N: Anulado; C: Confirmado (Mapa); ' ': Default
	 */
	public final TableField<PresupuestoRecord, String> ESTADO = createField("estado", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaulted(true), this, "A: Aprobado; R: Rechazado; N: Anulado; C: Confirmado (Mapa); ' ': Default");

	/**
	 * The column <code>matera.presupuesto.fecha</code>.
	 */
	public final TableField<PresupuestoRecord, Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>matera.presupuesto.id_zona</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_ZONA = createField("id_zona", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_entidad</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_ENTIDAD = createField("id_entidad", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_lugarCirugia</code>. id_entidad
	 */
	public final TableField<PresupuestoRecord, Integer> ID_LUGARCIRUGIA = createField("id_lugarCirugia", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "id_entidad");

	/**
	 * The column <code>matera.presupuesto.acompañamiento</code>.
	 */
	public final TableField<PresupuestoRecord, String> ACOMPAÑAMIENTO = createField("acompañamiento", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.fechaApertura</code>.
	 */
	public final TableField<PresupuestoRecord, Date> FECHAAPERTURA = createField("fechaApertura", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>matera.presupuesto.horaApertura</code>.
	 */
	public final TableField<PresupuestoRecord, String> HORAAPERTURA = createField("horaApertura", org.jooq.impl.SQLDataType.VARCHAR.length(4).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.expediente</code>.
	 */
	public final TableField<PresupuestoRecord, String> EXPEDIENTE = createField("expediente", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.contratacion</code>.
	 */
	public final TableField<PresupuestoRecord, String> CONTRATACION = createField("contratacion", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.paciente</code>.
	 */
	public final TableField<PresupuestoRecord, String> PACIENTE = createField("paciente", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.vip</code>.
	 */
	public final TableField<PresupuestoRecord, String> VIP = createField("vip", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.dni</code>.
	 */
	public final TableField<PresupuestoRecord, String> DNI = createField("dni", org.jooq.impl.SQLDataType.VARCHAR.length(15).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.direccion</code>.
	 */
	public final TableField<PresupuestoRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.telefono</code>.
	 */
	public final TableField<PresupuestoRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.total</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_profesional1</code>. id_profesional
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PROFESIONAL1 = createField("id_profesional1", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "id_profesional");

	/**
	 * The column <code>matera.presupuesto.rm1</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> RM1 = createField("rm1", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_profesional2</code>. id_profesional
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PROFESIONAL2 = createField("id_profesional2", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "id_profesional");

	/**
	 * The column <code>matera.presupuesto.rm2</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> RM2 = createField("rm2", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_profesional3</code>. id_profesional
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PROFESIONAL3 = createField("id_profesional3", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "id_profesional");

	/**
	 * The column <code>matera.presupuesto.rm3</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> RM3 = createField("rm3", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_vendedor</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_VENDEDOR = createField("id_vendedor", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_tipoOperacion</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_TIPOOPERACION = createField("id_tipoOperacion", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_formaPago</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_FORMAPAGO = createField("id_formaPago", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.formaPagoOtro</code>.
	 */
	public final TableField<PresupuestoRecord, String> FORMAPAGOOTRO = createField("formaPagoOtro", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_plazo</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PLAZO = createField("id_plazo", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.plazoOtro</code>.
	 */
	public final TableField<PresupuestoRecord, String> PLAZOOTRO = createField("plazoOtro", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_mantenimiento</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_MANTENIMIENTO = createField("id_mantenimiento", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.mantenimientoOtro</code>.
	 */
	public final TableField<PresupuestoRecord, String> MANTENIMIENTOOTRO = createField("mantenimientoOtro", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.notaPresu</code>.
	 */
	public final TableField<PresupuestoRecord, String> NOTAPRESU = createField("notaPresu", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.notaExtra</code>.
	 */
	public final TableField<PresupuestoRecord, String> NOTAEXTRA = createField("notaExtra", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.observaciones</code>.
	 */
	public final TableField<PresupuestoRecord, String> OBSERVACIONES = createField("observaciones", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.id_motivo</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_MOTIVO = createField("id_motivo", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.motivo</code>.
	 */
	public final TableField<PresupuestoRecord, String> MOTIVO = createField("motivo", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.fechaAgenda</code>.
	 */
	public final TableField<PresupuestoRecord, Date> FECHAAGENDA = createField("fechaAgenda", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>matera.presupuesto.id_tecnico</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_TECNICO = createField("id_tecnico", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_prestacion</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PRESTACION = createField("id_prestacion", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.importePrestacion</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> IMPORTEPRESTACION = createField("importePrestacion", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.fechaCirugia</code>.
	 */
	public final TableField<PresupuestoRecord, Date> FECHACIRUGIA = createField("fechaCirugia", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>matera.presupuesto.fechaAprobacion</code>.
	 */
	public final TableField<PresupuestoRecord, Date> FECHAAPROBACION = createField("fechaAprobacion", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>matera.presupuesto.competencia</code>.
	 */
	public final TableField<PresupuestoRecord, String> COMPETENCIA = createField("competencia", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.lobby</code>.
	 */
	public final TableField<PresupuestoRecord, String> LOBBY = createField("lobby", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>matera.presupuesto.desactivado</code>.
	 */
	public final TableField<PresupuestoRecord, String> DESACTIVADO = createField("desactivado", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_empresa</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.fechareal</code>.
	 */
	public final TableField<PresupuestoRecord, Timestamp> FECHAREAL = createField("fechareal", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.usuario</code>.
	 */
	public final TableField<PresupuestoRecord, String> USUARIO = createField("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.costo_venta</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> COSTO_VENTA = createField("costo_venta", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), this, "");

	/**
	 * The column <code>matera.presupuesto.rm4</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> RM4 = createField("rm4", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.rm5</code>.
	 */
	public final TableField<PresupuestoRecord, BigDecimal> RM5 = createField("rm5", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2).defaulted(true), this, "");

	/**
	 * The column <code>matera.presupuesto.id_profesional4</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PROFESIONAL4 = createField("id_profesional4", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>matera.presupuesto.id_profesional5</code>.
	 */
	public final TableField<PresupuestoRecord, Integer> ID_PROFESIONAL5 = createField("id_profesional5", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>matera.presupuesto</code> table reference
	 */
	public Presupuesto() {
		this("presupuesto", null);
	}

	/**
	 * Create an aliased <code>matera.presupuesto</code> table reference
	 */
	public Presupuesto(String alias) {
		this(alias, PRESUPUESTO);
	}

	private Presupuesto(String alias, Table<PresupuestoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Presupuesto(String alias, Table<PresupuestoRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PresupuestoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PRESUPUESTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PresupuestoRecord> getPrimaryKey() {
		return Keys.KEY_PRESUPUESTO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PresupuestoRecord>> getKeys() {
		return Arrays.<UniqueKey<PresupuestoRecord>>asList(Keys.KEY_PRESUPUESTO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Presupuesto as(String alias) {
		return new Presupuesto(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Presupuesto rename(String name) {
		return new Presupuesto(name, null);
	}
}
