/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.Keys;
import matera.jooq.Matera;
import matera.jooq.tables.records.TrackingolpRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trackingolp extends TableImpl<TrackingolpRecord> {

	private static final long serialVersionUID = -1868187075;

	/**
	 * The reference instance of <code>matera.trackingOLP</code>
	 */
	public static final Trackingolp TRACKINGOLP = new Trackingolp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TrackingolpRecord> getRecordType() {
		return TrackingolpRecord.class;
	}

	/**
	 * The column <code>matera.trackingOLP.id_liquidacion</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> ID_LIQUIDACION = createField("id_liquidacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>matera.trackingOLP.step1</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> STEP1 = createField("step1", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.trackingOLP.step2</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> STEP2 = createField("step2", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.trackingOLP.step3</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> STEP3 = createField("step3", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.trackingOLP.step4</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> STEP4 = createField("step4", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>matera.trackingOLP.step5</code>.
	 */
	public final TableField<TrackingolpRecord, Integer> STEP5 = createField("step5", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>matera.trackingOLP</code> table reference
	 */
	public Trackingolp() {
		this("trackingOLP", null);
	}

	/**
	 * Create an aliased <code>matera.trackingOLP</code> table reference
	 */
	public Trackingolp(String alias) {
		this(alias, TRACKINGOLP);
	}

	private Trackingolp(String alias, Table<TrackingolpRecord> aliased) {
		this(alias, aliased, null);
	}

	private Trackingolp(String alias, Table<TrackingolpRecord> aliased, Field<?>[] parameters) {
		super(alias, Matera.MATERA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TrackingolpRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TRACKINGOLP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TrackingolpRecord> getPrimaryKey() {
		return Keys.KEY_TRACKINGOLP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TrackingolpRecord>> getKeys() {
		return Arrays.<UniqueKey<TrackingolpRecord>>asList(Keys.KEY_TRACKINGOLP_PRIMARY, Keys.KEY_TRACKINGOLP_UNIQUE_ID_TRACKINGOLP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TrackingolpRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TrackingolpRecord, ?>>asList(Keys.LNK_LIQUIDACION_OLP_TRACKINGOLP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Trackingolp as(String alias) {
		return new Trackingolp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Trackingolp rename(String name) {
		return new Trackingolp(name, null);
	}
}
