/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Ajustestock;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "ajustestock", schema = "matera")
public class AjustestockRecord extends UpdatableRecordImpl<AjustestockRecord> implements Record6<Integer, Integer, Date, Integer, String, Timestamp> {

	private static final long serialVersionUID = -1456568183;

	/**
	 * Setter for <code>matera.ajustestock.id_ajusteStock</code>.
	 */
	public void setIdAjustestock(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.id_ajusteStock</code>.
	 */
	@Id
	@Column(name = "id_ajusteStock", unique = true, nullable = false, precision = 10)
	public Integer getIdAjustestock() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.ajustestock.id_zona</code>.
	 */
	public void setIdZona(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.id_zona</code>.
	 */
	@Column(name = "id_zona", precision = 10)
	public Integer getIdZona() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.ajustestock.fecha</code>.
	 */
	public void setFecha(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.fecha</code>.
	 */
	@Column(name = "fecha")
	public Date getFecha() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>matera.ajustestock.id_empresa</code>.
	 */
	public void setIdEmpresa(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.id_empresa</code>.
	 */
	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>matera.ajustestock.usuario</code>.
	 */
	public void setUsuario(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.usuario</code>.
	 */
	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>matera.ajustestock.fechaReal</code>.
	 */
	public void setFechareal(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.ajustestock.fechaReal</code>.
	 */
	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Date, Integer, String, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Date, Integer, String, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Ajustestock.AJUSTESTOCK.ID_AJUSTESTOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Ajustestock.AJUSTESTOCK.ID_ZONA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return Ajustestock.AJUSTESTOCK.FECHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Ajustestock.AJUSTESTOCK.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Ajustestock.AJUSTESTOCK.USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Ajustestock.AJUSTESTOCK.FECHAREAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdAjustestock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdZona();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getFecha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getFechareal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value1(Integer value) {
		setIdAjustestock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value2(Integer value) {
		setIdZona(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value3(Date value) {
		setFecha(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value4(Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value5(String value) {
		setUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord value6(Timestamp value) {
		setFechareal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AjustestockRecord values(Integer value1, Integer value2, Date value3, Integer value4, String value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AjustestockRecord
	 */
	public AjustestockRecord() {
		super(Ajustestock.AJUSTESTOCK);
	}

	/**
	 * Create a detached, initialised AjustestockRecord
	 */
	public AjustestockRecord(Integer idAjustestock, Integer idZona, Date fecha, Integer idEmpresa, String usuario, Timestamp fechareal) {
		super(Ajustestock.AJUSTESTOCK);

		setValue(0, idAjustestock);
		setValue(1, idZona);
		setValue(2, fecha);
		setValue(3, idEmpresa);
		setValue(4, usuario);
		setValue(5, fechareal);
	}
}
