/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Cajadeposito;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "cajadeposito", schema = "matera")
public class CajadepositoRecord extends UpdatableRecordImpl<CajadepositoRecord> implements Record6<Integer, Integer, Integer, String, String, Integer> {

	private static final long serialVersionUID = 1787416237;

	/**
	 * Setter for <code>matera.cajadeposito.id_cajaDeposito</code>.
	 */
	public void setIdCajadeposito(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.id_cajaDeposito</code>.
	 */
	@Id
	@Column(name = "id_cajaDeposito", unique = true, nullable = false, precision = 10)
	public Integer getIdCajadeposito() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.cajadeposito.id_zona</code>.
	 */
	public void setIdZona(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.id_zona</code>.
	 */
	@Column(name = "id_zona", nullable = false, precision = 10)
	public Integer getIdZona() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.cajadeposito.id_caja</code>.
	 */
	public void setIdCaja(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.id_caja</code>.
	 */
	@Column(name = "id_caja", nullable = false, precision = 10)
	public Integer getIdCaja() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>matera.cajadeposito.codigo</code>.
	 */
	public void setCodigo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.codigo</code>.
	 */
	@Column(name = "codigo", nullable = false, length = 25)
	public String getCodigo() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>matera.cajadeposito.habilita</code>.
	 */
	public void setHabilita(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.habilita</code>.
	 */
	@Column(name = "habilita", nullable = false, length = 1)
	public String getHabilita() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>matera.cajadeposito.id_empresa</code>.
	 */
	public void setIdEmpresa(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.cajadeposito.id_empresa</code>.
	 */
	@Column(name = "id_empresa", nullable = false, precision = 10)
	public Integer getIdEmpresa() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, String, String, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, String, String, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Cajadeposito.CAJADEPOSITO.ID_CAJADEPOSITO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Cajadeposito.CAJADEPOSITO.ID_ZONA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Cajadeposito.CAJADEPOSITO.ID_CAJA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Cajadeposito.CAJADEPOSITO.CODIGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Cajadeposito.CAJADEPOSITO.HABILITA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Cajadeposito.CAJADEPOSITO.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdCajadeposito();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdZona();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdCaja();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCodigo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getHabilita();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value1(Integer value) {
		setIdCajadeposito(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value2(Integer value) {
		setIdZona(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value3(Integer value) {
		setIdCaja(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value4(String value) {
		setCodigo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value5(String value) {
		setHabilita(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord value6(Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CajadepositoRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CajadepositoRecord
	 */
	public CajadepositoRecord() {
		super(Cajadeposito.CAJADEPOSITO);
	}

	/**
	 * Create a detached, initialised CajadepositoRecord
	 */
	public CajadepositoRecord(Integer idCajadeposito, Integer idZona, Integer idCaja, String codigo, String habilita, Integer idEmpresa) {
		super(Cajadeposito.CAJADEPOSITO);

		setValue(0, idCajadeposito);
		setValue(1, idZona);
		setValue(2, idCaja);
		setValue(3, codigo);
		setValue(4, habilita);
		setValue(5, idEmpresa);
	}
        
        @Override
        public String toString() {
            return getCodigo();
        }
}
