/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Emailrecipters;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "emailrecipters", schema = "matera")
public class EmailreciptersRecord extends UpdatableRecordImpl<EmailreciptersRecord> implements Record6<Integer, UInteger, Integer, String, Integer, Integer> {

	private static final long serialVersionUID = 104018408;

	/**
	 * Setter for <code>matera.emailrecipters.idEmailRecipters</code>.
	 */
	public void setIdemailrecipters(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.idEmailRecipters</code>.
	 */
	@Column(name = "idEmailRecipters", unique = true, nullable = false, precision = 10)
        @Id
	public Integer getIdemailrecipters() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.emailrecipters.idUsuario</code>.
	 */
	public void setIdusuario(UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.idUsuario</code>.
	 */
	@Column(name = "idUsuario", nullable = false, precision = 10)
	public UInteger getIdusuario() {
		return (UInteger) getValue(1);
	}

	/**
	 * Setter for <code>matera.emailrecipters.idModulo</code>.
	 */
	public void setIdmodulo(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.idModulo</code>.
	 */
	@Column(name = "idModulo", nullable = false, precision = 10)
	public Integer getIdmodulo() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>matera.emailrecipters.emailAddress</code>.
	 */
	public void setEmailaddress(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.emailAddress</code>.
	 */
	@Column(name = "emailAddress", nullable = false, length = 255)
	public String getEmailaddress() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>matera.emailrecipters.enabled</code>.
	 */
	public void setEnabled(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.enabled</code>.
	 */
	@Column(name = "enabled", nullable = false, precision = 10)
	public Integer getEnabled() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>matera.emailrecipters.idZona</code>.
	 */
	public void setIdzona(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.emailrecipters.idZona</code>.
	 */
	@Column(name = "idZona", nullable = false, precision = 10)
	public Integer getIdzona() {
		return (Integer) getValue(5);
	}
        
        // -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UInteger> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, UInteger, Integer, String, Integer, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, UInteger, Integer, String, Integer, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Emailrecipters.EMAILRECIPTERS.IDEMAILRECIPTERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field2() {
		return Emailrecipters.EMAILRECIPTERS.IDUSUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Emailrecipters.EMAILRECIPTERS.IDMODULO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Emailrecipters.EMAILRECIPTERS.EMAILADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Emailrecipters.EMAILRECIPTERS.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Emailrecipters.EMAILRECIPTERS.IDZONA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdemailrecipters();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value2() {
		return getIdusuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdmodulo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEmailaddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIdzona();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value1(Integer value) {
		setIdemailrecipters(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value2(UInteger value) {
		setIdusuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value3(Integer value) {
		setIdmodulo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value4(String value) {
		setEmailaddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value5(Integer value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord value6(Integer value) {
		setIdzona(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailreciptersRecord values(Integer value1, UInteger value2, Integer value3, String value4, Integer value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailreciptersRecord
	 */
	public EmailreciptersRecord() {
		super(Emailrecipters.EMAILRECIPTERS);
	}

	/**
	 * Create a detached, initialised EmailreciptersRecord
	 */
	public EmailreciptersRecord(Integer idemailrecipters, Integer idusuario, Integer idmodulo, String emailaddress, Integer enabled, Integer idzona) {
		super(Emailrecipters.EMAILRECIPTERS);

		setValue(0, idemailrecipters);
		setValue(1, idusuario);
		setValue(2, idmodulo);
		setValue(3, emailaddress);
		setValue(4, enabled);
		setValue(5, idzona);
	}
        
        public boolean getEnabledBool(){
            return getEnabled() == 1;
        }
}
