/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.HistoricoPrecioProducto;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "historico_precio_producto", schema = "matera")
public class HistoricoPrecioProductoRecord extends UpdatableRecordImpl<HistoricoPrecioProductoRecord> implements Record7<Integer, Integer, BigDecimal, BigDecimal, Timestamp, Integer, UInteger> {

	private static final long serialVersionUID = 500422151;

	/**
	 * Setter for <code>matera.historico_precio_producto.id_historico_precio_producto</code>.
	 */
	public void setIdHistoricoPrecioProducto(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.id_historico_precio_producto</code>.
	 */
	@Id
	@Column(name = "id_historico_precio_producto", unique = true, nullable = false, precision = 10)
	public Integer getIdHistoricoPrecioProducto() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.id_producto</code>.
	 */
	public void setIdProducto(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.id_producto</code>.
	 */
	@Column(name = "id_producto", nullable = false, precision = 10)
	public Integer getIdProducto() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.precio_anterior</code>.
	 */
	public void setPrecioAnterior(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.precio_anterior</code>.
	 */
	@Column(name = "precio_anterior", precision = 12, scale = 3)
	public BigDecimal getPrecioAnterior() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.precio_nuevo</code>.
	 */
	public void setPrecioNuevo(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.precio_nuevo</code>.
	 */
	@Column(name = "precio_nuevo", precision = 12, scale = 3)
	public BigDecimal getPrecioNuevo() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.fecha_actualizacion</code>.
	 */
	public void setFechaActualizacion(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.fecha_actualizacion</code>.
	 */
	@Column(name = "fecha_actualizacion", nullable = false)
	public Timestamp getFechaActualizacion() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.id_stock</code>.
	 */
	public void setIdStock(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.id_stock</code>.
	 */
	@Column(name = "id_stock", precision = 10)
	public Integer getIdStock() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>matera.historico_precio_producto.id_usuario</code>.
	 */
	public void setIdUsuario(UInteger value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>matera.historico_precio_producto.id_usuario</code>.
	 */
	@Column(name = "id_usuario", nullable = false, precision = 10)
	public UInteger getIdUsuario() {
		return (UInteger) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, BigDecimal, BigDecimal, Timestamp, Integer, UInteger> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, BigDecimal, BigDecimal, Timestamp, Integer, UInteger> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.ID_HISTORICO_PRECIO_PRODUCTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.ID_PRODUCTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.PRECIO_ANTERIOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.PRECIO_NUEVO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.FECHA_ACTUALIZACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.ID_STOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field7() {
		return HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO.ID_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdHistoricoPrecioProducto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdProducto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getPrecioAnterior();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getPrecioNuevo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getFechaActualizacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIdStock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value7() {
		return getIdUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value1(Integer value) {
		setIdHistoricoPrecioProducto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value2(Integer value) {
		setIdProducto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value3(BigDecimal value) {
		setPrecioAnterior(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value4(BigDecimal value) {
		setPrecioNuevo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value5(Timestamp value) {
		setFechaActualizacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value6(Integer value) {
		setIdStock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord value7(UInteger value) {
		setIdUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HistoricoPrecioProductoRecord values(Integer value1, Integer value2, BigDecimal value3, BigDecimal value4, Timestamp value5, Integer value6, UInteger value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HistoricoPrecioProductoRecord
	 */
	public HistoricoPrecioProductoRecord() {
		super(HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO);
	}

	/**
	 * Create a detached, initialised HistoricoPrecioProductoRecord
	 */
	public HistoricoPrecioProductoRecord(Integer idHistoricoPrecioProducto, Integer idProducto, BigDecimal precioAnterior, BigDecimal precioNuevo, Timestamp fechaActualizacion, Integer idStock, UInteger idUsuario) {
		super(HistoricoPrecioProducto.HISTORICO_PRECIO_PRODUCTO);

		setValue(0, idHistoricoPrecioProducto);
		setValue(1, idProducto);
		setValue(2, precioAnterior);
		setValue(3, precioNuevo);
		setValue(4, fechaActualizacion);
		setValue(5, idStock);
		setValue(6, idUsuario);
	}
}
