/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Intersucursalcaja;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "intersucursalcaja", schema = "matera")
public class IntersucursalcajaRecord extends UpdatableRecordImpl<IntersucursalcajaRecord> implements Record4<Integer, Integer, Integer, String> {

	private static final long serialVersionUID = 131512863;

	/**
	 * Setter for <code>matera.intersucursalcaja.id_intersucursalCaja</code>.
	 */
	public void setIdIntersucursalcaja(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.intersucursalcaja.id_intersucursalCaja</code>.
	 */
	@Id
	@Column(name = "id_intersucursalCaja", unique = true, nullable = false, precision = 10)
	public Integer getIdIntersucursalcaja() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.intersucursalcaja.id_intersucursal</code>.
	 */
	public void setIdIntersucursal(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.intersucursalcaja.id_intersucursal</code>.
	 */
	@Column(name = "id_intersucursal", precision = 10)
	public Integer getIdIntersucursal() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.intersucursalcaja.id_cajaDeposito</code>.
	 */
	public void setIdCajadeposito(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.intersucursalcaja.id_cajaDeposito</code>.
	 */
	@Column(name = "id_cajaDeposito", precision = 10)
	public Integer getIdCajadeposito() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>matera.intersucursalcaja.devuelto</code>.
	 */
	public void setDevuelto(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.intersucursalcaja.devuelto</code>.
	 */
	@Column(name = "devuelto", length = 1)
	public String getDevuelto() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Intersucursalcaja.INTERSUCURSALCAJA.ID_INTERSUCURSALCAJA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Intersucursalcaja.INTERSUCURSALCAJA.ID_INTERSUCURSAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Intersucursalcaja.INTERSUCURSALCAJA.ID_CAJADEPOSITO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Intersucursalcaja.INTERSUCURSALCAJA.DEVUELTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdIntersucursalcaja();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdIntersucursal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdCajadeposito();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDevuelto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntersucursalcajaRecord value1(Integer value) {
		setIdIntersucursalcaja(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntersucursalcajaRecord value2(Integer value) {
		setIdIntersucursal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntersucursalcajaRecord value3(Integer value) {
		setIdCajadeposito(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntersucursalcajaRecord value4(String value) {
		setDevuelto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IntersucursalcajaRecord values(Integer value1, Integer value2, Integer value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IntersucursalcajaRecord
	 */
	public IntersucursalcajaRecord() {
		super(Intersucursalcaja.INTERSUCURSALCAJA);
	}

	/**
	 * Create a detached, initialised IntersucursalcajaRecord
	 */
	public IntersucursalcajaRecord(Integer idIntersucursalcaja, Integer idIntersucursal, Integer idCajadeposito, String devuelto) {
		super(Intersucursalcaja.INTERSUCURSALCAJA);

		setValue(0, idIntersucursalcaja);
		setValue(1, idIntersucursal);
		setValue(2, idCajadeposito);
		setValue(3, devuelto);
	}
}
