/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Liquidaciondetalle;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "liquidaciondetalle", schema = "matera")
public class LiquidaciondetalleRecord extends UpdatableRecordImpl<LiquidaciondetalleRecord> implements Record9<Integer, Integer, String, String, Date, BigDecimal, Integer, String, Timestamp> {

	private static final long serialVersionUID = 1789322722;

	/**
	 * Setter for <code>matera.liquidaciondetalle.id_liquidacionDetalle</code>.
	 */
	public void setIdLiquidaciondetalle(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.id_liquidacionDetalle</code>.
	 */
	@Id
	@Column(name = "id_liquidacionDetalle", unique = true, nullable = false, precision = 10)
	public Integer getIdLiquidaciondetalle() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.id_liquidacion</code>.
	 */
	public void setIdLiquidacion(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.id_liquidacion</code>.
	 */
	@Column(name = "id_liquidacion", precision = 10)
	public Integer getIdLiquidacion() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.banco</code>.
	 */
	public void setBanco(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.banco</code>.
	 */
	@Column(name = "banco", length = 45)
	public String getBanco() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.cheque</code>.
	 */
	public void setCheque(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.cheque</code>.
	 */
	@Column(name = "cheque", length = 45)
	public String getCheque() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.vencimiento</code>.
	 */
	public void setVencimiento(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.vencimiento</code>.
	 */
	@Column(name = "vencimiento")
	public Date getVencimiento() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.importe</code>.
	 */
	public void setImporte(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.importe</code>.
	 */
	@Column(name = "importe", precision = 7, scale = 2)
	public BigDecimal getImporte() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.id_empresa</code>.
	 */
	public void setIdEmpresa(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.id_empresa</code>.
	 */
	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.usuario</code>.
	 */
	public void setUsuario(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.usuario</code>.
	 */
	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>matera.liquidaciondetalle.fechaReal</code>.
	 */
	public void setFechareal(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>matera.liquidaciondetalle.fechaReal</code>.
	 */
	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return (Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Integer, String, String, Date, BigDecimal, Integer, String, Timestamp> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Integer, String, String, Date, BigDecimal, Integer, String, Timestamp> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.ID_LIQUIDACIONDETALLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.ID_LIQUIDACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.BANCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.CHEQUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.VENCIMIENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.IMPORTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Liquidaciondetalle.LIQUIDACIONDETALLE.FECHAREAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdLiquidaciondetalle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdLiquidacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getBanco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCheque();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getVencimiento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getImporte();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getFechareal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value1(Integer value) {
		setIdLiquidaciondetalle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value2(Integer value) {
		setIdLiquidacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value3(String value) {
		setBanco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value4(String value) {
		setCheque(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value5(Date value) {
		setVencimiento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value6(BigDecimal value) {
		setImporte(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value7(Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value8(String value) {
		setUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord value9(Timestamp value) {
		setFechareal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidaciondetalleRecord values(Integer value1, Integer value2, String value3, String value4, Date value5, BigDecimal value6, Integer value7, String value8, Timestamp value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LiquidaciondetalleRecord
	 */
	public LiquidaciondetalleRecord() {
		super(Liquidaciondetalle.LIQUIDACIONDETALLE);
	}

	/**
	 * Create a detached, initialised LiquidaciondetalleRecord
	 */
	public LiquidaciondetalleRecord(Integer idLiquidaciondetalle, Integer idLiquidacion, String banco, String cheque, Date vencimiento, BigDecimal importe, Integer idEmpresa, String usuario, Timestamp fechareal) {
		super(Liquidaciondetalle.LIQUIDACIONDETALLE);

		setValue(0, idLiquidaciondetalle);
		setValue(1, idLiquidacion);
		setValue(2, banco);
		setValue(3, cheque);
		setValue(4, vencimiento);
		setValue(5, importe);
		setValue(6, idEmpresa);
		setValue(7, usuario);
		setValue(8, fechareal);
	}
}
