/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Opcion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "opcion", schema = "matera")
public class OpcionRecord extends UpdatableRecordImpl<OpcionRecord> implements Record5<Integer, Integer, String, String, String> {

	private static final long serialVersionUID = 1099551239;

	/**
	 * Setter for <code>matera.opcion.id_opcion</code>.
	 */
	public void setIdOpcion(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.opcion.id_opcion</code>.
	 */
	@Id
	@Column(name = "id_opcion", unique = true, nullable = false, precision = 10)
	public Integer getIdOpcion() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.opcion.grupo</code>.
	 */
	public void setGrupo(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.opcion.grupo</code>.
	 */
	@Column(name = "grupo", nullable = false, precision = 10)
	public Integer getGrupo() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.opcion.nombre</code>.
	 */
	public void setNombre(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.opcion.nombre</code>.
	 */
	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>matera.opcion.habilita</code>.
	 */
	public void setHabilita(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.opcion.habilita</code>.
	 */
	@Column(name = "habilita", nullable = false, length = 1)
	public String getHabilita() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>matera.opcion.abreviado</code>.
	 */
	public void setAbreviado(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.opcion.abreviado</code>.
	 */
	@Column(name = "abreviado", nullable = false, length = 10)
	public String getAbreviado() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Opcion.OPCION.ID_OPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Opcion.OPCION.GRUPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Opcion.OPCION.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Opcion.OPCION.HABILITA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Opcion.OPCION.ABREVIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdOpcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getGrupo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getHabilita();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAbreviado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord value1(Integer value) {
		setIdOpcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord value2(Integer value) {
		setGrupo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord value3(String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord value4(String value) {
		setHabilita(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord value5(String value) {
		setAbreviado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OpcionRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OpcionRecord
	 */
	public OpcionRecord() {
		super(Opcion.OPCION);
	}

	/**
	 * Create a detached, initialised OpcionRecord
	 */
	public OpcionRecord(Integer idOpcion, Integer grupo, String nombre, String habilita, String abreviado) {
		super(Opcion.OPCION);

		setValue(0, idOpcion);
		setValue(1, grupo);
		setValue(2, nombre);
		setValue(3, habilita);
		setValue(4, abreviado);
	}
        
        @Override
        public String toString() {
            return getNombre();
        }
}
