/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Trackingolp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "trackingOLP", schema = "matera")
public class TrackingolpRecord extends UpdatableRecordImpl<TrackingolpRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = 607273285;

	/**
	 * Setter for <code>matera.trackingOLP.id_liquidacion</code>.
	 */
	public void setIdLiquidacion(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.id_liquidacion</code>.
	 */
	@Id
	@Column(name = "id_liquidacion", unique = true, nullable = false, precision = 10)
	public Integer getIdLiquidacion() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>matera.trackingOLP.step1</code>.
	 */
	public void setStep1(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.step1</code>.
	 */
	@Column(name = "step1", nullable = false, precision = 10)
	public Integer getStep1() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>matera.trackingOLP.step2</code>.
	 */
	public void setStep2(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.step2</code>.
	 */
	@Column(name = "step2", nullable = false, precision = 10)
	public Integer getStep2() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>matera.trackingOLP.step3</code>.
	 */
	public void setStep3(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.step3</code>.
	 */
	@Column(name = "step3", nullable = false, precision = 10)
	public Integer getStep3() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>matera.trackingOLP.step4</code>.
	 */
	public void setStep4(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.step4</code>.
	 */
	@Column(name = "step4", nullable = false, precision = 10)
	public Integer getStep4() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>matera.trackingOLP.step5</code>.
	 */
	public void setStep5(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.trackingOLP.step5</code>.
	 */
	@Column(name = "step5", nullable = false, precision = 10)
	public Integer getStep5() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Trackingolp.TRACKINGOLP.ID_LIQUIDACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Trackingolp.TRACKINGOLP.STEP1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Trackingolp.TRACKINGOLP.STEP2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Trackingolp.TRACKINGOLP.STEP3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Trackingolp.TRACKINGOLP.STEP4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Trackingolp.TRACKINGOLP.STEP5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdLiquidacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStep1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getStep2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getStep3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getStep4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getStep5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value1(Integer value) {
		setIdLiquidacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value2(Integer value) {
		setStep1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value3(Integer value) {
		setStep2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value4(Integer value) {
		setStep3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value5(Integer value) {
		setStep4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord value6(Integer value) {
		setStep5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrackingolpRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrackingolpRecord
	 */
	public TrackingolpRecord() {
		super(Trackingolp.TRACKINGOLP);
	}

	/**
	 * Create a detached, initialised TrackingolpRecord
	 */
	public TrackingolpRecord(Integer idLiquidacion, Integer step1, Integer step2, Integer step3, Integer step4, Integer step5) {
		super(Trackingolp.TRACKINGOLP);

		setValue(0, idLiquidacion);
		setValue(1, step1);
		setValue(2, step2);
		setValue(3, step3);
		setValue(4, step4);
		setValue(5, step5);
	}

        public Boolean step1() {
		return getStep1() == 1;
	}
        
        public Boolean step2() {
		return getStep2() == 1;
	}
        
        public Boolean step3() {
		return getStep3() == 1;
	}
        
        public Boolean step4() {
		return getStep4() == 1;
	}
        
        public Boolean step5() {
		return getStep5() == 1;
	}
        
}
