/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.records;


import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import matera.jooq.tables.Usuario;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "usuario", schema = "matera")
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> implements Record19<UInteger, String, String, String, Date, String, String, Integer, Integer, Integer, Date, Date, String, String, String, Integer, Integer, String, Integer> {

	private static final long serialVersionUID = 579344022;

	/**
	 * Setter for <code>matera.usuario.id_usuario</code>.
	 */
	public void setIdUsuario(UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_usuario</code>.
	 */
	@Id
	@Column(name = "id_usuario", unique = true, nullable = false, precision = 10)
	public UInteger getIdUsuario() {
		return (UInteger) getValue(0);
	}

	/**
	 * Setter for <code>matera.usuario.nombre</code>.
	 */
	public void setNombre(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matera.usuario.nombre</code>.
	 */
	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>matera.usuario.documento</code>.
	 */
	public void setDocumento(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matera.usuario.documento</code>.
	 */
	@Column(name = "documento", length = 10)
	public String getDocumento() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>matera.usuario.cuil</code>.
	 */
	public void setCuil(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matera.usuario.cuil</code>.
	 */
	@Column(name = "cuil", length = 11)
	public String getCuil() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>matera.usuario.fechaNac</code>.
	 */
	public void setFechanac(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matera.usuario.fechaNac</code>.
	 */
	@Column(name = "fechaNac")
	public Date getFechanac() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>matera.usuario.direccion</code>.
	 */
	public void setDireccion(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matera.usuario.direccion</code>.
	 */
	@Column(name = "direccion", length = 100)
	public String getDireccion() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>matera.usuario.codPostal</code>.
	 */
	public void setCodpostal(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>matera.usuario.codPostal</code>.
	 */
	@Column(name = "codPostal", length = 10)
	public String getCodpostal() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>matera.usuario.id_provincia</code>.
	 */
	public void setIdProvincia(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_provincia</code>.
	 */
	@Column(name = "id_provincia", precision = 10)
	public Integer getIdProvincia() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>matera.usuario.id_departamento</code>.
	 */
	public void setIdDepartamento(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_departamento</code>.
	 */
	@Column(name = "id_departamento", precision = 10)
	public Integer getIdDepartamento() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>matera.usuario.id_localidad</code>.
	 */
	public void setIdLocalidad(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_localidad</code>.
	 */
	@Column(name = "id_localidad", precision = 10)
	public Integer getIdLocalidad() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>matera.usuario.fechaIngreso</code>.
	 */
	public void setFechaingreso(Date value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>matera.usuario.fechaIngreso</code>.
	 */
	@Column(name = "fechaIngreso")
	public Date getFechaingreso() {
		return (Date) getValue(10);
	}

	/**
	 * Setter for <code>matera.usuario.fechaEgreso</code>.
	 */
	public void setFechaegreso(Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>matera.usuario.fechaEgreso</code>.
	 */
	@Column(name = "fechaEgreso")
	public Date getFechaegreso() {
		return (Date) getValue(11);
	}

	/**
	 * Setter for <code>matera.usuario.usaSistema</code>.
	 */
	public void setUsasistema(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>matera.usuario.usaSistema</code>.
	 */
	@Column(name = "usaSistema", length = 1)
	public String getUsasistema() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>matera.usuario.contraseña</code>.
	 */
	public void setContraseña(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>matera.usuario.contraseña</code>.
	 */
	@Column(name = "contraseña", length = 15)
	public String getContraseña() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>matera.usuario.email</code>.
	 */
	public void setEmail(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>matera.usuario.email</code>.
	 */
	@Column(name = "email", length = 45)
	public String getEmail() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>matera.usuario.id_zona</code>.
	 */
	public void setIdZona(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_zona</code>.
	 */
	@Column(name = "id_zona", precision = 10)
	public Integer getIdZona() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>matera.usuario.id_zonaSistema</code>.
	 */
	public void setIdZonasistema(Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_zonaSistema</code>.
	 */
	@Column(name = "id_zonaSistema", precision = 10)
	public Integer getIdZonasistema() {
		return (Integer) getValue(16);
	}

	/**
	 * Setter for <code>matera.usuario.habilita</code>.
	 */
	public void setHabilita(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>matera.usuario.habilita</code>.
	 */
	@Column(name = "habilita", length = 1)
	public String getHabilita() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>matera.usuario.id_empresa</code>.
	 */
	public void setIdEmpresa(Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>matera.usuario.id_empresa</code>.
	 */
	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return (Integer) getValue(18);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UInteger> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record19 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<UInteger, String, String, String, Date, String, String, Integer, Integer, Integer, Date, Date, String, String, String, Integer, Integer, String, Integer> fieldsRow() {
		return (Row19) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<UInteger, String, String, String, Date, String, String, Integer, Integer, Integer, Date, Date, String, String, String, Integer, Integer, String, Integer> valuesRow() {
		return (Row19) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field1() {
		return Usuario.USUARIO.ID_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Usuario.USUARIO.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Usuario.USUARIO.DOCUMENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Usuario.USUARIO.CUIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Usuario.USUARIO.FECHANAC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Usuario.USUARIO.DIRECCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Usuario.USUARIO.CODPOSTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Usuario.USUARIO.ID_PROVINCIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Usuario.USUARIO.ID_DEPARTAMENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Usuario.USUARIO.ID_LOCALIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field11() {
		return Usuario.USUARIO.FECHAINGRESO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field12() {
		return Usuario.USUARIO.FECHAEGRESO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Usuario.USUARIO.USASISTEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return Usuario.USUARIO.CONTRASEÑA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return Usuario.USUARIO.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Usuario.USUARIO.ID_ZONA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field17() {
		return Usuario.USUARIO.ID_ZONASISTEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field18() {
		return Usuario.USUARIO.HABILITA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field19() {
		return Usuario.USUARIO.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value1() {
		return getIdUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDocumento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCuil();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getFechanac();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getDireccion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getCodpostal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getIdProvincia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getIdDepartamento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getIdLocalidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value11() {
		return getFechaingreso();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value12() {
		return getFechaegreso();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getUsasistema();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getContraseña();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getIdZona();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value17() {
		return getIdZonasistema();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value18() {
		return getHabilita();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value19() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value1(UInteger value) {
		setIdUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value2(String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value3(String value) {
		setDocumento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value4(String value) {
		setCuil(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value5(Date value) {
		setFechanac(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value6(String value) {
		setDireccion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value7(String value) {
		setCodpostal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value8(Integer value) {
		setIdProvincia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value9(Integer value) {
		setIdDepartamento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value10(Integer value) {
		setIdLocalidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value11(Date value) {
		setFechaingreso(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value12(Date value) {
		setFechaegreso(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value13(String value) {
		setUsasistema(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value14(String value) {
		setContraseña(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value15(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value16(Integer value) {
		setIdZona(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value17(Integer value) {
		setIdZonasistema(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value18(String value) {
		setHabilita(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value19(Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord values(UInteger value1, String value2, String value3, String value4, Date value5, String value6, String value7, Integer value8, Integer value9, Integer value10, Date value11, Date value12, String value13, String value14, String value15, Integer value16, Integer value17, String value18, Integer value19) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsuarioRecord
	 */
	public UsuarioRecord() {
		super(Usuario.USUARIO);
	}

	/**
	 * Create a detached, initialised UsuarioRecord
	 */
	public UsuarioRecord(UInteger idUsuario, String nombre, String documento, String cuil, Date fechanac, String direccion, String codpostal, Integer idProvincia, Integer idDepartamento, Integer idLocalidad, Date fechaingreso, Date fechaegreso, String usasistema, String contraseña, String email, Integer idZona, Integer idZonasistema, String habilita, Integer idEmpresa) {
		super(Usuario.USUARIO);

		setValue(0, idUsuario);
		setValue(1, nombre);
		setValue(2, documento);
		setValue(3, cuil);
		setValue(4, fechanac);
		setValue(5, direccion);
		setValue(6, codpostal);
		setValue(7, idProvincia);
		setValue(8, idDepartamento);
		setValue(9, idLocalidad);
		setValue(10, fechaingreso);
		setValue(11, fechaegreso);
		setValue(12, usasistema);
		setValue(13, contraseña);
		setValue(14, email);
		setValue(15, idZona);
		setValue(16, idZonasistema);
		setValue(17, habilita);
		setValue(18, idEmpresa);
	}
        
    @Override
    public String toString() {
        return getNombre();
    }
}
