/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "acceso", schema = "matera")
public class Acceso implements Serializable {

	private static final long serialVersionUID = -628966242;

	private UInteger idAcceso;
	private UInteger idUsuario;
	private UInteger idMenu;
	private Integer  idEmpresa;

	public Acceso() {}

	public Acceso(Acceso value) {
		this.idAcceso = value.idAcceso;
		this.idUsuario = value.idUsuario;
		this.idMenu = value.idMenu;
		this.idEmpresa = value.idEmpresa;
	}

	public Acceso(
		UInteger idAcceso,
		UInteger idUsuario,
		UInteger idMenu,
		Integer  idEmpresa
	) {
		this.idAcceso = idAcceso;
		this.idUsuario = idUsuario;
		this.idMenu = idMenu;
		this.idEmpresa = idEmpresa;
	}

	@Id
	@Column(name = "id_acceso", unique = true, nullable = false, precision = 10)
	public UInteger getIdAcceso() {
		return this.idAcceso;
	}

	public void setIdAcceso(UInteger idAcceso) {
		this.idAcceso = idAcceso;
	}

	@Column(name = "id_usuario", nullable = false, precision = 10)
	public UInteger getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(UInteger idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_menu", nullable = false, precision = 10)
	public UInteger getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(UInteger idMenu) {
		this.idMenu = idMenu;
	}

	@Column(name = "id_empresa", nullable = false, precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Acceso (");

		sb.append(idAcceso);
		sb.append(", ").append(idUsuario);
		sb.append(", ").append(idMenu);
		sb.append(", ").append(idEmpresa);

		sb.append(")");
		return sb.toString();
	}
}
