/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "cajacomposicion", schema = "matera")
public class Cajacomposicion implements Serializable {

	private static final long serialVersionUID = -610783411;

	private Integer   idCajacomposicion;
	private Integer   idCajadeposito;
	private Integer   idProducto;
	private Integer   cantidad;
	private String    usuario;
	private Timestamp fechareal;

	public Cajacomposicion() {}

	public Cajacomposicion(Cajacomposicion value) {
		this.idCajacomposicion = value.idCajacomposicion;
		this.idCajadeposito = value.idCajadeposito;
		this.idProducto = value.idProducto;
		this.cantidad = value.cantidad;
		this.usuario = value.usuario;
		this.fechareal = value.fechareal;
	}

	public Cajacomposicion(
		Integer   idCajacomposicion,
		Integer   idCajadeposito,
		Integer   idProducto,
		Integer   cantidad,
		String    usuario,
		Timestamp fechareal
	) {
		this.idCajacomposicion = idCajacomposicion;
		this.idCajadeposito = idCajadeposito;
		this.idProducto = idProducto;
		this.cantidad = cantidad;
		this.usuario = usuario;
		this.fechareal = fechareal;
	}

	@Id
	@Column(name = "id_cajaComposicion", unique = true, nullable = false, precision = 10)
	public Integer getIdCajacomposicion() {
		return this.idCajacomposicion;
	}

	public void setIdCajacomposicion(Integer idCajacomposicion) {
		this.idCajacomposicion = idCajacomposicion;
	}

	@Column(name = "id_cajaDeposito", precision = 10)
	public Integer getIdCajadeposito() {
		return this.idCajadeposito;
	}

	public void setIdCajadeposito(Integer idCajadeposito) {
		this.idCajadeposito = idCajadeposito;
	}

	@Column(name = "id_producto", precision = 10)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "cantidad", precision = 10)
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Cajacomposicion (");

		sb.append(idCajacomposicion);
		sb.append(", ").append(idCajadeposito);
		sb.append(", ").append(idProducto);
		sb.append(", ").append(cantidad);
		sb.append(", ").append(usuario);
		sb.append(", ").append(fechareal);

		sb.append(")");
		return sb.toString();
	}
}
