/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "cotizacion", schema = "matera")
public class Cotizacion implements Serializable {

	private static final long serialVersionUID = 1257065879;

	private Integer    idCotizacion;
	private Integer    idMoneda;
	private Integer    mes;
	private Integer    año;
	private BigDecimal valor;
	private Integer    idEmpresa;
	private String     usuario;
	private Timestamp  fechareal;

	public Cotizacion() {}

	public Cotizacion(Cotizacion value) {
		this.idCotizacion = value.idCotizacion;
		this.idMoneda = value.idMoneda;
		this.mes = value.mes;
		this.año = value.año;
		this.valor = value.valor;
		this.idEmpresa = value.idEmpresa;
		this.usuario = value.usuario;
		this.fechareal = value.fechareal;
	}

	public Cotizacion(
		Integer    idCotizacion,
		Integer    idMoneda,
		Integer    mes,
		Integer    año,
		BigDecimal valor,
		Integer    idEmpresa,
		String     usuario,
		Timestamp  fechareal
	) {
		this.idCotizacion = idCotizacion;
		this.idMoneda = idMoneda;
		this.mes = mes;
		this.año = año;
		this.valor = valor;
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
		this.fechareal = fechareal;
	}

	@Id
	@Column(name = "id_cotizacion", unique = true, nullable = false, precision = 10)
	public Integer getIdCotizacion() {
		return this.idCotizacion;
	}

	public void setIdCotizacion(Integer idCotizacion) {
		this.idCotizacion = idCotizacion;
	}

	@Column(name = "id_moneda", precision = 10)
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "mes", precision = 10)
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "año", precision = 10)
	public Integer getAño() {
		return this.año;
	}

	public void setAño(Integer año) {
		this.año = año;
	}

	@Column(name = "valor", precision = 12, scale = 3)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Cotizacion (");

		sb.append(idCotizacion);
		sb.append(", ").append(idMoneda);
		sb.append(", ").append(mes);
		sb.append(", ").append(año);
		sb.append(", ").append(valor);
		sb.append(", ").append(idEmpresa);
		sb.append(", ").append(usuario);
		sb.append(", ").append(fechareal);

		sb.append(")");
		return sb.toString();
	}
}
