/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "emailrecipters", schema = "matera")
public class Emailrecipters implements Serializable {

	private static final long serialVersionUID = 1143320836;

	private Integer idemailrecipters;
	private Integer idmodulo;
	private Integer idUsuario;
	private String  emailaddress;
	private Integer enabled;

	public Emailrecipters() {}

	public Emailrecipters(Emailrecipters value) {
		this.idemailrecipters = value.idemailrecipters;
		this.idmodulo = value.idmodulo;
		this.idUsuario = value.idUsuario;
		this.emailaddress = value.emailaddress;
		this.enabled = value.enabled;
	}

	public Emailrecipters(
		Integer idemailrecipters,
		Integer idmodulo,
		Integer idUsuario,
		String  emailaddress,
		Integer enabled
	) {
		this.idemailrecipters = idemailrecipters;
		this.idmodulo = idmodulo;
		this.idUsuario = idUsuario;
		this.emailaddress = emailaddress;
		this.enabled = enabled;
	}

	@Id
	@Column(name = "idEmailRecipters", unique = true, nullable = false, precision = 10)
	public Integer getIdemailrecipters() {
		return this.idemailrecipters;
	}

	public void setIdemailrecipters(Integer idemailrecipters) {
		this.idemailrecipters = idemailrecipters;
	}

	@Column(name = "idModulo", nullable = false, precision = 10)
	public Integer getIdmodulo() {
		return this.idmodulo;
	}

	public void setIdmodulo(Integer idmodulo) {
		this.idmodulo = idmodulo;
	}

	@Column(name = "id_usuario", nullable = false, precision = 10)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "emailAddress", nullable = false, length = 255)
	public String getEmailaddress() {
		return this.emailaddress;
	}

	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	@Column(name = "enabled", nullable = false, precision = 10)
	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Emailrecipters (");

		sb.append(idemailrecipters);
		sb.append(", ").append(idmodulo);
		sb.append(", ").append(idUsuario);
		sb.append(", ").append(emailaddress);
		sb.append(", ").append(enabled);

		sb.append(")");
		return sb.toString();
	}
}
