/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "factura", schema = "matera")
public class Factura implements Serializable {

	private static final long serialVersionUID = 1298622265;

	private Integer    idFactura;
	private Date       fecha;
	private Integer    idPresupuesto;
	private Integer    idTipocomp;
	private String     numcomp;
	private Integer    idTipocomprel;
	private String     numcomprel;
	private Date       vencimiento;
	private Integer    idFormapago;
	private String     dc;
	private BigDecimal bonificacion;
	private BigDecimal neto;
	private BigDecimal aliperciibb;
	private BigDecimal perciibb;
	private BigDecimal aliiva;
	private BigDecimal iva;
	private String     observaciones;
	private Integer    idVendedor;
	private String     comparte;
	private Integer    idVendedorcomparte;
	private Integer    idEmpresa;
	private String     usuario;
	private Timestamp  fechareal;

	public Factura() {}

	public Factura(Factura value) {
		this.idFactura = value.idFactura;
		this.fecha = value.fecha;
		this.idPresupuesto = value.idPresupuesto;
		this.idTipocomp = value.idTipocomp;
		this.numcomp = value.numcomp;
		this.idTipocomprel = value.idTipocomprel;
		this.numcomprel = value.numcomprel;
		this.vencimiento = value.vencimiento;
		this.idFormapago = value.idFormapago;
		this.dc = value.dc;
		this.bonificacion = value.bonificacion;
		this.neto = value.neto;
		this.aliperciibb = value.aliperciibb;
		this.perciibb = value.perciibb;
		this.aliiva = value.aliiva;
		this.iva = value.iva;
		this.observaciones = value.observaciones;
		this.idVendedor = value.idVendedor;
		this.comparte = value.comparte;
		this.idVendedorcomparte = value.idVendedorcomparte;
		this.idEmpresa = value.idEmpresa;
		this.usuario = value.usuario;
		this.fechareal = value.fechareal;
	}

	public Factura(
		Integer    idFactura,
		Date       fecha,
		Integer    idPresupuesto,
		Integer    idTipocomp,
		String     numcomp,
		Integer    idTipocomprel,
		String     numcomprel,
		Date       vencimiento,
		Integer    idFormapago,
		String     dc,
		BigDecimal bonificacion,
		BigDecimal neto,
		BigDecimal aliperciibb,
		BigDecimal perciibb,
		BigDecimal aliiva,
		BigDecimal iva,
		String     observaciones,
		Integer    idVendedor,
		String     comparte,
		Integer    idVendedorcomparte,
		Integer    idEmpresa,
		String     usuario,
		Timestamp  fechareal
	) {
		this.idFactura = idFactura;
		this.fecha = fecha;
		this.idPresupuesto = idPresupuesto;
		this.idTipocomp = idTipocomp;
		this.numcomp = numcomp;
		this.idTipocomprel = idTipocomprel;
		this.numcomprel = numcomprel;
		this.vencimiento = vencimiento;
		this.idFormapago = idFormapago;
		this.dc = dc;
		this.bonificacion = bonificacion;
		this.neto = neto;
		this.aliperciibb = aliperciibb;
		this.perciibb = perciibb;
		this.aliiva = aliiva;
		this.iva = iva;
		this.observaciones = observaciones;
		this.idVendedor = idVendedor;
		this.comparte = comparte;
		this.idVendedorcomparte = idVendedorcomparte;
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
		this.fechareal = fechareal;
	}

	@Id
	@Column(name = "id_factura", unique = true, nullable = false, precision = 10)
	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	@Column(name = "fecha")
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_presupuesto", precision = 10)
	public Integer getIdPresupuesto() {
		return this.idPresupuesto;
	}

	public void setIdPresupuesto(Integer idPresupuesto) {
		this.idPresupuesto = idPresupuesto;
	}

	@Column(name = "id_tipoComp", precision = 10)
	public Integer getIdTipocomp() {
		return this.idTipocomp;
	}

	public void setIdTipocomp(Integer idTipocomp) {
		this.idTipocomp = idTipocomp;
	}

	@Column(name = "numComp", length = 12)
	public String getNumcomp() {
		return this.numcomp;
	}

	public void setNumcomp(String numcomp) {
		this.numcomp = numcomp;
	}

	@Column(name = "id_tipoCompRel", precision = 10)
	public Integer getIdTipocomprel() {
		return this.idTipocomprel;
	}

	public void setIdTipocomprel(Integer idTipocomprel) {
		this.idTipocomprel = idTipocomprel;
	}

	@Column(name = "numCompRel", length = 12)
	public String getNumcomprel() {
		return this.numcomprel;
	}

	public void setNumcomprel(String numcomprel) {
		this.numcomprel = numcomprel;
	}

	@Column(name = "vencimiento")
	public Date getVencimiento() {
		return this.vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	@Column(name = "id_formaPago", precision = 10)
	public Integer getIdFormapago() {
		return this.idFormapago;
	}

	public void setIdFormapago(Integer idFormapago) {
		this.idFormapago = idFormapago;
	}

	@Column(name = "dc", length = 1)
	public String getDc() {
		return this.dc;
	}

	public void setDc(String dc) {
		this.dc = dc;
	}

	@Column(name = "bonificacion", precision = 9, scale = 2)
	public BigDecimal getBonificacion() {
		return this.bonificacion;
	}

	public void setBonificacion(BigDecimal bonificacion) {
		this.bonificacion = bonificacion;
	}

	@Column(name = "neto", precision = 9, scale = 2)
	public BigDecimal getNeto() {
		return this.neto;
	}

	public void setNeto(BigDecimal neto) {
		this.neto = neto;
	}

	@Column(name = "aliPercIIBB", precision = 5, scale = 2)
	public BigDecimal getAliperciibb() {
		return this.aliperciibb;
	}

	public void setAliperciibb(BigDecimal aliperciibb) {
		this.aliperciibb = aliperciibb;
	}

	@Column(name = "percIIBB", precision = 9, scale = 2)
	public BigDecimal getPerciibb() {
		return this.perciibb;
	}

	public void setPerciibb(BigDecimal perciibb) {
		this.perciibb = perciibb;
	}

	@Column(name = "aliIva", precision = 5, scale = 2)
	public BigDecimal getAliiva() {
		return this.aliiva;
	}

	public void setAliiva(BigDecimal aliiva) {
		this.aliiva = aliiva;
	}

	@Column(name = "iva", precision = 9, scale = 2)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "id_vendedor", precision = 10)
	public Integer getIdVendedor() {
		return this.idVendedor;
	}

	public void setIdVendedor(Integer idVendedor) {
		this.idVendedor = idVendedor;
	}

	@Column(name = "comparte", length = 1)
	public String getComparte() {
		return this.comparte;
	}

	public void setComparte(String comparte) {
		this.comparte = comparte;
	}

	@Column(name = "id_vendedorComparte", precision = 10)
	public Integer getIdVendedorcomparte() {
		return this.idVendedorcomparte;
	}

	public void setIdVendedorcomparte(Integer idVendedorcomparte) {
		this.idVendedorcomparte = idVendedorcomparte;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Factura (");

		sb.append(idFactura);
		sb.append(", ").append(fecha);
		sb.append(", ").append(idPresupuesto);
		sb.append(", ").append(idTipocomp);
		sb.append(", ").append(numcomp);
		sb.append(", ").append(idTipocomprel);
		sb.append(", ").append(numcomprel);
		sb.append(", ").append(vencimiento);
		sb.append(", ").append(idFormapago);
		sb.append(", ").append(dc);
		sb.append(", ").append(bonificacion);
		sb.append(", ").append(neto);
		sb.append(", ").append(aliperciibb);
		sb.append(", ").append(perciibb);
		sb.append(", ").append(aliiva);
		sb.append(", ").append(iva);
		sb.append(", ").append(observaciones);
		sb.append(", ").append(idVendedor);
		sb.append(", ").append(comparte);
		sb.append(", ").append(idVendedorcomparte);
		sb.append(", ").append(idEmpresa);
		sb.append(", ").append(usuario);
		sb.append(", ").append(fechareal);

		sb.append(")");
		return sb.toString();
	}
}
