/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "historico_precio_producto", schema = "matera")
public class HistoricoPrecioProducto implements Serializable {

	private static final long serialVersionUID = 697165797;

	private Integer    idHistoricoPrecioProducto;
	private Integer    idProducto;
	private BigDecimal precioAnterior;
	private BigDecimal precioNuevo;
	private Timestamp  fechaActualizacion;
	private Integer    idStock;
	private UInteger   idUsuario;

	public HistoricoPrecioProducto() {}

	public HistoricoPrecioProducto(HistoricoPrecioProducto value) {
		this.idHistoricoPrecioProducto = value.idHistoricoPrecioProducto;
		this.idProducto = value.idProducto;
		this.precioAnterior = value.precioAnterior;
		this.precioNuevo = value.precioNuevo;
		this.fechaActualizacion = value.fechaActualizacion;
		this.idStock = value.idStock;
		this.idUsuario = value.idUsuario;
	}

	public HistoricoPrecioProducto(
		Integer    idHistoricoPrecioProducto,
		Integer    idProducto,
		BigDecimal precioAnterior,
		BigDecimal precioNuevo,
		Timestamp  fechaActualizacion,
		Integer    idStock,
		UInteger   idUsuario
	) {
		this.idHistoricoPrecioProducto = idHistoricoPrecioProducto;
		this.idProducto = idProducto;
		this.precioAnterior = precioAnterior;
		this.precioNuevo = precioNuevo;
		this.fechaActualizacion = fechaActualizacion;
		this.idStock = idStock;
		this.idUsuario = idUsuario;
	}

	@Id
	@Column(name = "id_historico_precio_producto", unique = true, nullable = false, precision = 10)
	public Integer getIdHistoricoPrecioProducto() {
		return this.idHistoricoPrecioProducto;
	}

	public void setIdHistoricoPrecioProducto(Integer idHistoricoPrecioProducto) {
		this.idHistoricoPrecioProducto = idHistoricoPrecioProducto;
	}

	@Column(name = "id_producto", nullable = false, precision = 10)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "precio_anterior", precision = 12, scale = 3)
	public BigDecimal getPrecioAnterior() {
		return this.precioAnterior;
	}

	public void setPrecioAnterior(BigDecimal precioAnterior) {
		this.precioAnterior = precioAnterior;
	}

	@Column(name = "precio_nuevo", precision = 12, scale = 3)
	public BigDecimal getPrecioNuevo() {
		return this.precioNuevo;
	}

	public void setPrecioNuevo(BigDecimal precioNuevo) {
		this.precioNuevo = precioNuevo;
	}

	@Column(name = "fecha_actualizacion", nullable = false)
	public Timestamp getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Timestamp fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "id_stock", precision = 10)
	public Integer getIdStock() {
		return this.idStock;
	}

	public void setIdStock(Integer idStock) {
		this.idStock = idStock;
	}

	@Column(name = "id_usuario", nullable = false, precision = 10)
	public UInteger getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(UInteger idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("HistoricoPrecioProducto (");

		sb.append(idHistoricoPrecioProducto);
		sb.append(", ").append(idProducto);
		sb.append(", ").append(precioAnterior);
		sb.append(", ").append(precioNuevo);
		sb.append(", ").append(fechaActualizacion);
		sb.append(", ").append(idStock);
		sb.append(", ").append(idUsuario);

		sb.append(")");
		return sb.toString();
	}
}
