/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "mayortecnico", schema = "matera")
public class Mayortecnico implements Serializable {

	private static final long serialVersionUID = 93392361;

	private Integer    idMayortecnico;
	private Date       fecha;
	private Integer    idPresupuesto;
	private Integer    idTecnico;
	private String     dc;
	private BigDecimal importe;
	private String     observaciones;
	private Integer    liquidacion;
	private Integer    idEmpresa;
	private String     usuario;
	private Timestamp  fechareal;

	public Mayortecnico() {}

	public Mayortecnico(Mayortecnico value) {
		this.idMayortecnico = value.idMayortecnico;
		this.fecha = value.fecha;
		this.idPresupuesto = value.idPresupuesto;
		this.idTecnico = value.idTecnico;
		this.dc = value.dc;
		this.importe = value.importe;
		this.observaciones = value.observaciones;
		this.liquidacion = value.liquidacion;
		this.idEmpresa = value.idEmpresa;
		this.usuario = value.usuario;
		this.fechareal = value.fechareal;
	}

	public Mayortecnico(
		Integer    idMayortecnico,
		Date       fecha,
		Integer    idPresupuesto,
		Integer    idTecnico,
		String     dc,
		BigDecimal importe,
		String     observaciones,
		Integer    liquidacion,
		Integer    idEmpresa,
		String     usuario,
		Timestamp  fechareal
	) {
		this.idMayortecnico = idMayortecnico;
		this.fecha = fecha;
		this.idPresupuesto = idPresupuesto;
		this.idTecnico = idTecnico;
		this.dc = dc;
		this.importe = importe;
		this.observaciones = observaciones;
		this.liquidacion = liquidacion;
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
		this.fechareal = fechareal;
	}

	@Id
	@Column(name = "id_mayorTecnico", unique = true, nullable = false, precision = 10)
	public Integer getIdMayortecnico() {
		return this.idMayortecnico;
	}

	public void setIdMayortecnico(Integer idMayortecnico) {
		this.idMayortecnico = idMayortecnico;
	}

	@Column(name = "fecha")
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_presupuesto", precision = 10)
	public Integer getIdPresupuesto() {
		return this.idPresupuesto;
	}

	public void setIdPresupuesto(Integer idPresupuesto) {
		this.idPresupuesto = idPresupuesto;
	}

	@Column(name = "id_tecnico", precision = 10)
	public Integer getIdTecnico() {
		return this.idTecnico;
	}

	public void setIdTecnico(Integer idTecnico) {
		this.idTecnico = idTecnico;
	}

	@Column(name = "dc", length = 1)
	public String getDc() {
		return this.dc;
	}

	public void setDc(String dc) {
		this.dc = dc;
	}

	@Column(name = "importe", precision = 7, scale = 2)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "liquidacion", precision = 10)
	public Integer getLiquidacion() {
		return this.liquidacion;
	}

	public void setLiquidacion(Integer liquidacion) {
		this.liquidacion = liquidacion;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Mayortecnico (");

		sb.append(idMayortecnico);
		sb.append(", ").append(fecha);
		sb.append(", ").append(idPresupuesto);
		sb.append(", ").append(idTecnico);
		sb.append(", ").append(dc);
		sb.append(", ").append(importe);
		sb.append(", ").append(observaciones);
		sb.append(", ").append(liquidacion);
		sb.append(", ").append(idEmpresa);
		sb.append(", ").append(usuario);
		sb.append(", ").append(fechareal);

		sb.append(")");
		return sb.toString();
	}
}
