/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "notapresu", schema = "matera")
public class Notapresu implements Serializable {

	private static final long serialVersionUID = 1079599169;

	private Integer   idNotapresu;
	private String    nota;
	private Integer   idEmpresa;
	private Timestamp fechareal;
	private String    usuario;

	public Notapresu() {}

	public Notapresu(Notapresu value) {
		this.idNotapresu = value.idNotapresu;
		this.nota = value.nota;
		this.idEmpresa = value.idEmpresa;
		this.fechareal = value.fechareal;
		this.usuario = value.usuario;
	}

	public Notapresu(
		Integer   idNotapresu,
		String    nota,
		Integer   idEmpresa,
		Timestamp fechareal,
		String    usuario
	) {
		this.idNotapresu = idNotapresu;
		this.nota = nota;
		this.idEmpresa = idEmpresa;
		this.fechareal = fechareal;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id_notaPresu", unique = true, nullable = false, precision = 10)
	public Integer getIdNotapresu() {
		return this.idNotapresu;
	}

	public void setIdNotapresu(Integer idNotapresu) {
		this.idNotapresu = idNotapresu;
	}

	@Column(name = "nota", length = 65535)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Notapresu (");

		sb.append(idNotapresu);
		sb.append(", ").append(nota);
		sb.append(", ").append(idEmpresa);
		sb.append(", ").append(fechareal);
		sb.append(", ").append(usuario);

		sb.append(")");
		return sb.toString();
	}
}
