/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "numeracionliquidaciones", schema = "matera")
public class Numeracionliquidaciones implements Serializable {

	private static final long serialVersionUID = -1428328086;

	private Integer idNumeracionliquidaciones;
	private Integer tecnico;
	private Integer profesional;
	private Integer vendedor;
	private Integer idEmpresa;

	public Numeracionliquidaciones() {}

	public Numeracionliquidaciones(Numeracionliquidaciones value) {
		this.idNumeracionliquidaciones = value.idNumeracionliquidaciones;
		this.tecnico = value.tecnico;
		this.profesional = value.profesional;
		this.vendedor = value.vendedor;
		this.idEmpresa = value.idEmpresa;
	}

	public Numeracionliquidaciones(
		Integer idNumeracionliquidaciones,
		Integer tecnico,
		Integer profesional,
		Integer vendedor,
		Integer idEmpresa
	) {
		this.idNumeracionliquidaciones = idNumeracionliquidaciones;
		this.tecnico = tecnico;
		this.profesional = profesional;
		this.vendedor = vendedor;
		this.idEmpresa = idEmpresa;
	}

	@Id
	@Column(name = "id_numeracionLiquidaciones", unique = true, nullable = false, precision = 10)
	public Integer getIdNumeracionliquidaciones() {
		return this.idNumeracionliquidaciones;
	}

	public void setIdNumeracionliquidaciones(Integer idNumeracionliquidaciones) {
		this.idNumeracionliquidaciones = idNumeracionliquidaciones;
	}

	@Column(name = "tecnico", precision = 10)
	public Integer getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Integer tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "profesional", precision = 10)
	public Integer getProfesional() {
		return this.profesional;
	}

	public void setProfesional(Integer profesional) {
		this.profesional = profesional;
	}

	@Column(name = "vendedor", precision = 10)
	public Integer getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Integer vendedor) {
		this.vendedor = vendedor;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Numeracionliquidaciones (");

		sb.append(idNumeracionliquidaciones);
		sb.append(", ").append(tecnico);
		sb.append(", ").append(profesional);
		sb.append(", ").append(vendedor);
		sb.append(", ").append(idEmpresa);

		sb.append(")");
		return sb.toString();
	}
}
