/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "prestacion", schema = "matera")
public class Prestacion implements Serializable {

	private static final long serialVersionUID = -1016158139;

	private Integer    idPrestacion;
	private String     nombre;
	private BigDecimal importe;
	private String     habilita;
	private Integer    idEmpresa;

	public Prestacion() {}

	public Prestacion(Prestacion value) {
		this.idPrestacion = value.idPrestacion;
		this.nombre = value.nombre;
		this.importe = value.importe;
		this.habilita = value.habilita;
		this.idEmpresa = value.idEmpresa;
	}

	public Prestacion(
		Integer    idPrestacion,
		String     nombre,
		BigDecimal importe,
		String     habilita,
		Integer    idEmpresa
	) {
		this.idPrestacion = idPrestacion;
		this.nombre = nombre;
		this.importe = importe;
		this.habilita = habilita;
		this.idEmpresa = idEmpresa;
	}

	@Id
	@Column(name = "id_prestacion", unique = true, nullable = false, precision = 10)
	public Integer getIdPrestacion() {
		return this.idPrestacion;
	}

	public void setIdPrestacion(Integer idPrestacion) {
		this.idPrestacion = idPrestacion;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "importe", nullable = false, precision = 9, scale = 2)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "habilita", nullable = false, length = 1)
	public String getHabilita() {
		return this.habilita;
	}

	public void setHabilita(String habilita) {
		this.habilita = habilita;
	}

	@Column(name = "id_empresa", nullable = false, precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Prestacion (");

		sb.append(idPrestacion);
		sb.append(", ").append(nombre);
		sb.append(", ").append(importe);
		sb.append(", ").append(habilita);
		sb.append(", ").append(idEmpresa);

		sb.append(")");
		return sb.toString();
	}
}
