/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "stock", schema = "matera")
public class Stock implements Serializable {

	private static final long serialVersionUID = -1504113303;

	private Integer   idStock;
	private Date      fecha;
	private Integer   idTipocomp;
	private String    numcomp;
	private Integer   idProveedor;
	private Integer   idZona;
	private String    observaciones;
	private String    chequeado;
	private Integer   idEmpresa;
	private String    usuario;
	private Timestamp fechareal;

	public Stock() {}

	public Stock(Stock value) {
		this.idStock = value.idStock;
		this.fecha = value.fecha;
		this.idTipocomp = value.idTipocomp;
		this.numcomp = value.numcomp;
		this.idProveedor = value.idProveedor;
		this.idZona = value.idZona;
		this.observaciones = value.observaciones;
		this.chequeado = value.chequeado;
		this.idEmpresa = value.idEmpresa;
		this.usuario = value.usuario;
		this.fechareal = value.fechareal;
	}

	public Stock(
		Integer   idStock,
		Date      fecha,
		Integer   idTipocomp,
		String    numcomp,
		Integer   idProveedor,
		Integer   idZona,
		String    observaciones,
		String    chequeado,
		Integer   idEmpresa,
		String    usuario,
		Timestamp fechareal
	) {
		this.idStock = idStock;
		this.fecha = fecha;
		this.idTipocomp = idTipocomp;
		this.numcomp = numcomp;
		this.idProveedor = idProveedor;
		this.idZona = idZona;
		this.observaciones = observaciones;
		this.chequeado = chequeado;
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
		this.fechareal = fechareal;
	}

	@Id
	@Column(name = "id_stock", unique = true, nullable = false, precision = 10)
	public Integer getIdStock() {
		return this.idStock;
	}

	public void setIdStock(Integer idStock) {
		this.idStock = idStock;
	}

	@Column(name = "fecha")
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "id_tipoComp", precision = 10)
	public Integer getIdTipocomp() {
		return this.idTipocomp;
	}

	public void setIdTipocomp(Integer idTipocomp) {
		this.idTipocomp = idTipocomp;
	}

	@Column(name = "numComp", length = 12)
	public String getNumcomp() {
		return this.numcomp;
	}

	public void setNumcomp(String numcomp) {
		this.numcomp = numcomp;
	}

	@Column(name = "id_proveedor", precision = 10)
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "id_zona", precision = 10)
	public Integer getIdZona() {
		return this.idZona;
	}

	public void setIdZona(Integer idZona) {
		this.idZona = idZona;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "chequeado", length = 1)
	public String getChequeado() {
		return this.chequeado;
	}

	public void setChequeado(String chequeado) {
		this.chequeado = chequeado;
	}

	@Column(name = "id_empresa", precision = 10)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fechaReal")
	public Timestamp getFechareal() {
		return this.fechareal;
	}

	public void setFechareal(Timestamp fechareal) {
		this.fechareal = fechareal;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Stock (");

		sb.append(idStock);
		sb.append(", ").append(fecha);
		sb.append(", ").append(idTipocomp);
		sb.append(", ").append(numcomp);
		sb.append(", ").append(idProveedor);
		sb.append(", ").append(idZona);
		sb.append(", ").append(observaciones);
		sb.append(", ").append(chequeado);
		sb.append(", ").append(idEmpresa);
		sb.append(", ").append(usuario);
		sb.append(", ").append(fechareal);

		sb.append(")");
		return sb.toString();
	}
}
