/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "stockdetalle", schema = "matera")
public class Stockdetalle implements Serializable {

	private static final long serialVersionUID = 1713426;

	private Integer    idStockdetalle;
	private Integer    idStock;
	private Integer    idRemito;
	private Integer    idAjustestock;
	private Integer    idProducto;
	private Integer    cantidad;
	private String     dc;
	private String     lote;
	private String     serie;
	private String     pm;
	private Date       vencimiento;
	private BigDecimal costopesos;
	private Integer    idMoneda;
	private BigDecimal cotizacion;
	private String     observaciones;
	private Integer    idZona;

	public Stockdetalle() {}

	public Stockdetalle(Stockdetalle value) {
		this.idStockdetalle = value.idStockdetalle;
		this.idStock = value.idStock;
		this.idRemito = value.idRemito;
		this.idAjustestock = value.idAjustestock;
		this.idProducto = value.idProducto;
		this.cantidad = value.cantidad;
		this.dc = value.dc;
		this.lote = value.lote;
		this.serie = value.serie;
		this.pm = value.pm;
		this.vencimiento = value.vencimiento;
		this.costopesos = value.costopesos;
		this.idMoneda = value.idMoneda;
		this.cotizacion = value.cotizacion;
		this.observaciones = value.observaciones;
		this.idZona = value.idZona;
	}

	public Stockdetalle(
		Integer    idStockdetalle,
		Integer    idStock,
		Integer    idRemito,
		Integer    idAjustestock,
		Integer    idProducto,
		Integer    cantidad,
		String     dc,
		String     lote,
		String     serie,
		String     pm,
		Date       vencimiento,
		BigDecimal costopesos,
		Integer    idMoneda,
		BigDecimal cotizacion,
		String     observaciones,
		Integer    idZona
	) {
		this.idStockdetalle = idStockdetalle;
		this.idStock = idStock;
		this.idRemito = idRemito;
		this.idAjustestock = idAjustestock;
		this.idProducto = idProducto;
		this.cantidad = cantidad;
		this.dc = dc;
		this.lote = lote;
		this.serie = serie;
		this.pm = pm;
		this.vencimiento = vencimiento;
		this.costopesos = costopesos;
		this.idMoneda = idMoneda;
		this.cotizacion = cotizacion;
		this.observaciones = observaciones;
		this.idZona = idZona;
	}

	@Id
	@Column(name = "id_stockDetalle", unique = true, nullable = false, precision = 10)
	public Integer getIdStockdetalle() {
		return this.idStockdetalle;
	}

	public void setIdStockdetalle(Integer idStockdetalle) {
		this.idStockdetalle = idStockdetalle;
	}

	@Column(name = "id_stock", precision = 10)
	public Integer getIdStock() {
		return this.idStock;
	}

	public void setIdStock(Integer idStock) {
		this.idStock = idStock;
	}

	@Column(name = "id_remito", precision = 10)
	public Integer getIdRemito() {
		return this.idRemito;
	}

	public void setIdRemito(Integer idRemito) {
		this.idRemito = idRemito;
	}

	@Column(name = "id_ajusteStock", precision = 10)
	public Integer getIdAjustestock() {
		return this.idAjustestock;
	}

	public void setIdAjustestock(Integer idAjustestock) {
		this.idAjustestock = idAjustestock;
	}

	@Column(name = "id_producto", precision = 10)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "cantidad", precision = 10)
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "dc", length = 1)
	public String getDc() {
		return this.dc;
	}

	public void setDc(String dc) {
		this.dc = dc;
	}

	@Column(name = "lote", length = 45)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "serie", length = 255)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "pm", length = 45)
	public String getPm() {
		return this.pm;
	}

	public void setPm(String pm) {
		this.pm = pm;
	}

	@Column(name = "vencimiento")
	public Date getVencimiento() {
		return this.vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	@Column(name = "costoPesos", precision = 12, scale = 2)
	public BigDecimal getCostopesos() {
		return this.costopesos;
	}

	public void setCostopesos(BigDecimal costopesos) {
		this.costopesos = costopesos;
	}

	@Column(name = "id_moneda", precision = 10)
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "cotizacion", precision = 12, scale = 3)
	public BigDecimal getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(BigDecimal cotizacion) {
		this.cotizacion = cotizacion;
	}

	@Column(name = "observaciones", length = 65535)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "id_zona", precision = 10)
	public Integer getIdZona() {
		return this.idZona;
	}

	public void setIdZona(Integer idZona) {
		this.idZona = idZona;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Stockdetalle (");

		sb.append(idStockdetalle);
		sb.append(", ").append(idStock);
		sb.append(", ").append(idRemito);
		sb.append(", ").append(idAjustestock);
		sb.append(", ").append(idProducto);
		sb.append(", ").append(cantidad);
		sb.append(", ").append(dc);
		sb.append(", ").append(lote);
		sb.append(", ").append(serie);
		sb.append(", ").append(pm);
		sb.append(", ").append(vencimiento);
		sb.append(", ").append(costopesos);
		sb.append(", ").append(idMoneda);
		sb.append(", ").append(cotizacion);
		sb.append(", ").append(observaciones);
		sb.append(", ").append(idZona);

		sb.append(")");
		return sb.toString();
	}
}
