/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.daos;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.tables.Cotizacion;
import matera.jooq.tables.records.CotizacionRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CotizacionDao extends DAOImpl<CotizacionRecord, matera.jooq.tables.pojos.Cotizacion, Integer> {

	/**
	 * Create a new CotizacionDao without any configuration
	 */
	public CotizacionDao() {
		super(Cotizacion.COTIZACION, matera.jooq.tables.pojos.Cotizacion.class);
	}

	/**
	 * Create a new CotizacionDao with an attached configuration
	 */
	@Autowired
	public CotizacionDao(Configuration configuration) {
		super(Cotizacion.COTIZACION, matera.jooq.tables.pojos.Cotizacion.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(matera.jooq.tables.pojos.Cotizacion object) {
		return object.getIdCotizacion();
	}

	/**
	 * Fetch records that have <code>id_cotizacion IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByIdCotizacion(Integer... values) {
		return fetch(Cotizacion.COTIZACION.ID_COTIZACION, values);
	}

	/**
	 * Fetch a unique record that has <code>id_cotizacion = value</code>
	 */
	public matera.jooq.tables.pojos.Cotizacion fetchOneByIdCotizacion(Integer value) {
		return fetchOne(Cotizacion.COTIZACION.ID_COTIZACION, value);
	}

	/**
	 * Fetch records that have <code>id_moneda IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByIdMoneda(Integer... values) {
		return fetch(Cotizacion.COTIZACION.ID_MONEDA, values);
	}

	/**
	 * Fetch records that have <code>mes IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByMes(Integer... values) {
		return fetch(Cotizacion.COTIZACION.MES, values);
	}

	/**
	 * Fetch records that have <code>año IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByAño(Integer... values) {
		return fetch(Cotizacion.COTIZACION.AÑO, values);
	}

	/**
	 * Fetch records that have <code>valor IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByValor(BigDecimal... values) {
		return fetch(Cotizacion.COTIZACION.VALOR, values);
	}

	/**
	 * Fetch records that have <code>id_empresa IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByIdEmpresa(Integer... values) {
		return fetch(Cotizacion.COTIZACION.ID_EMPRESA, values);
	}

	/**
	 * Fetch records that have <code>usuario IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByUsuario(String... values) {
		return fetch(Cotizacion.COTIZACION.USUARIO, values);
	}

	/**
	 * Fetch records that have <code>fechaReal IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Cotizacion> fetchByFechareal(Timestamp... values) {
		return fetch(Cotizacion.COTIZACION.FECHAREAL, values);
	}
}
