/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.daos;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.tables.Estrategia;
import matera.jooq.tables.records.EstrategiaRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class EstrategiaDao extends DAOImpl<EstrategiaRecord, matera.jooq.tables.pojos.Estrategia, Integer> {

	/**
	 * Create a new EstrategiaDao without any configuration
	 */
	public EstrategiaDao() {
		super(Estrategia.ESTRATEGIA, matera.jooq.tables.pojos.Estrategia.class);
	}

	/**
	 * Create a new EstrategiaDao with an attached configuration
	 */
	@Autowired
	public EstrategiaDao(Configuration configuration) {
		super(Estrategia.ESTRATEGIA, matera.jooq.tables.pojos.Estrategia.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(matera.jooq.tables.pojos.Estrategia object) {
		return object.getIdEstrategia();
	}

	/**
	 * Fetch records that have <code>id_estrategia IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByIdEstrategia(Integer... values) {
		return fetch(Estrategia.ESTRATEGIA.ID_ESTRATEGIA, values);
	}

	/**
	 * Fetch a unique record that has <code>id_estrategia = value</code>
	 */
	public matera.jooq.tables.pojos.Estrategia fetchOneByIdEstrategia(Integer value) {
		return fetchOne(Estrategia.ESTRATEGIA.ID_ESTRATEGIA, value);
	}

	/**
	 * Fetch records that have <code>id_profesional IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByIdProfesional(Integer... values) {
		return fetch(Estrategia.ESTRATEGIA.ID_PROFESIONAL, values);
	}

	/**
	 * Fetch records that have <code>fechaInicio IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByFechainicio(Date... values) {
		return fetch(Estrategia.ESTRATEGIA.FECHAINICIO, values);
	}

	/**
	 * Fetch records that have <code>fechaAgenda IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByFechaagenda(Date... values) {
		return fetch(Estrategia.ESTRATEGIA.FECHAAGENDA, values);
	}

	/**
	 * Fetch records that have <code>perfil IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByPerfil(String... values) {
		return fetch(Estrategia.ESTRATEGIA.PERFIL, values);
	}

	/**
	 * Fetch records that have <code>estrategia IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByEstrategia(String... values) {
		return fetch(Estrategia.ESTRATEGIA.ESTRATEGIA_, values);
	}

	/**
	 * Fetch records that have <code>respuesta IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByRespuesta(String... values) {
		return fetch(Estrategia.ESTRATEGIA.RESPUESTA, values);
	}

	/**
	 * Fetch records that have <code>historico IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByHistorico(String... values) {
		return fetch(Estrategia.ESTRATEGIA.HISTORICO, values);
	}

	/**
	 * Fetch records that have <code>id_empresa IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByIdEmpresa(Integer... values) {
		return fetch(Estrategia.ESTRATEGIA.ID_EMPRESA, values);
	}

	/**
	 * Fetch records that have <code>usuario IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByUsuario(String... values) {
		return fetch(Estrategia.ESTRATEGIA.USUARIO, values);
	}

	/**
	 * Fetch records that have <code>fechaReal IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Estrategia> fetchByFechareal(Timestamp... values) {
		return fetch(Estrategia.ESTRATEGIA.FECHAREAL, values);
	}
}
