/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.tables.Notapresu;
import matera.jooq.tables.records.NotapresuRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class NotapresuDao extends DAOImpl<NotapresuRecord, matera.jooq.tables.pojos.Notapresu, Integer> {

	/**
	 * Create a new NotapresuDao without any configuration
	 */
	public NotapresuDao() {
		super(Notapresu.NOTAPRESU, matera.jooq.tables.pojos.Notapresu.class);
	}

	/**
	 * Create a new NotapresuDao with an attached configuration
	 */
	@Autowired
	public NotapresuDao(Configuration configuration) {
		super(Notapresu.NOTAPRESU, matera.jooq.tables.pojos.Notapresu.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(matera.jooq.tables.pojos.Notapresu object) {
		return object.getIdNotapresu();
	}

	/**
	 * Fetch records that have <code>id_notaPresu IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Notapresu> fetchByIdNotapresu(Integer... values) {
		return fetch(Notapresu.NOTAPRESU.ID_NOTAPRESU, values);
	}

	/**
	 * Fetch a unique record that has <code>id_notaPresu = value</code>
	 */
	public matera.jooq.tables.pojos.Notapresu fetchOneByIdNotapresu(Integer value) {
		return fetchOne(Notapresu.NOTAPRESU.ID_NOTAPRESU, value);
	}

	/**
	 * Fetch records that have <code>nota IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Notapresu> fetchByNota(String... values) {
		return fetch(Notapresu.NOTAPRESU.NOTA, values);
	}

	/**
	 * Fetch records that have <code>id_empresa IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Notapresu> fetchByIdEmpresa(Integer... values) {
		return fetch(Notapresu.NOTAPRESU.ID_EMPRESA, values);
	}

	/**
	 * Fetch records that have <code>fechaReal IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Notapresu> fetchByFechareal(Timestamp... values) {
		return fetch(Notapresu.NOTAPRESU.FECHAREAL, values);
	}

	/**
	 * Fetch records that have <code>usuario IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Notapresu> fetchByUsuario(String... values) {
		return fetch(Notapresu.NOTAPRESU.USUARIO, values);
	}
}
