/**
 * This class is generated by jOOQ
 */
package matera.jooq.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import matera.jooq.tables.Reclamo;
import matera.jooq.tables.records.ReclamoRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ReclamoDao extends DAOImpl<ReclamoRecord, matera.jooq.tables.pojos.Reclamo, Integer> {

	/**
	 * Create a new ReclamoDao without any configuration
	 */
	public ReclamoDao() {
		super(Reclamo.RECLAMO, matera.jooq.tables.pojos.Reclamo.class);
	}

	/**
	 * Create a new ReclamoDao with an attached configuration
	 */
	@Autowired
	public ReclamoDao(Configuration configuration) {
		super(Reclamo.RECLAMO, matera.jooq.tables.pojos.Reclamo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(matera.jooq.tables.pojos.Reclamo object) {
		return object.getIdReclamo();
	}

	/**
	 * Fetch records that have <code>id_reclamo IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdReclamo(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_RECLAMO, values);
	}

	/**
	 * Fetch a unique record that has <code>id_reclamo = value</code>
	 */
	public matera.jooq.tables.pojos.Reclamo fetchOneByIdReclamo(Integer value) {
		return fetchOne(Reclamo.RECLAMO.ID_RECLAMO, value);
	}

	/**
	 * Fetch records that have <code>fechaReclamo IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFechareclamo(Date... values) {
		return fetch(Reclamo.RECLAMO.FECHARECLAMO, values);
	}

	/**
	 * Fetch records that have <code>id_presupuesto IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdPresupuesto(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_PRESUPUESTO, values);
	}

	/**
	 * Fetch records that have <code>descripcion IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByDescripcion(String... values) {
		return fetch(Reclamo.RECLAMO.DESCRIPCION, values);
	}

	/**
	 * Fetch records that have <code>procedimiento IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByProcedimiento(String... values) {
		return fetch(Reclamo.RECLAMO.PROCEDIMIENTO, values);
	}

	/**
	 * Fetch records that have <code>acciones IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByAcciones(String... values) {
		return fetch(Reclamo.RECLAMO.ACCIONES, values);
	}

	/**
	 * Fetch records that have <code>fechaNotificacion IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFechanotificacion(Date... values) {
		return fetch(Reclamo.RECLAMO.FECHANOTIFICACION, values);
	}

	/**
	 * Fetch records that have <code>fechaDevolucion IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFechadevolucion(Date... values) {
		return fetch(Reclamo.RECLAMO.FECHADEVOLUCION, values);
	}

	/**
	 * Fetch records that have <code>id_reclamoInterno IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdReclamointerno(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_RECLAMOINTERNO, values);
	}

	/**
	 * Fetch records that have <code>id_reclamoExterno IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdReclamoexterno(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_RECLAMOEXTERNO, values);
	}

	/**
	 * Fetch records that have <code>direccion IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByDireccion(String... values) {
		return fetch(Reclamo.RECLAMO.DIRECCION, values);
	}

	/**
	 * Fetch records that have <code>telefono IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByTelefono(Integer... values) {
		return fetch(Reclamo.RECLAMO.TELEFONO, values);
	}

	/**
	 * Fetch records that have <code>recibe IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByRecibe(String... values) {
		return fetch(Reclamo.RECLAMO.RECIBE, values);
	}

	/**
	 * Fetch records that have <code>id_usuario IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdUsuario(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_USUARIO, values);
	}

	/**
	 * Fetch records that have <code>id_zona IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByIdZona(Integer... values) {
		return fetch(Reclamo.RECLAMO.ID_ZONA, values);
	}

	/**
	 * Fetch records that have <code>destinoReclamo IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByDestinoreclamo(String... values) {
		return fetch(Reclamo.RECLAMO.DESTINORECLAMO, values);
	}

	/**
	 * Fetch records that have <code>file1 IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFile1(byte[]... values) {
		return fetch(Reclamo.RECLAMO.FILE1, values);
	}

	/**
	 * Fetch records that have <code>file2 IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFile2(byte[]... values) {
		return fetch(Reclamo.RECLAMO.FILE2, values);
	}

	/**
	 * Fetch records that have <code>file3 IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFile3(byte[]... values) {
		return fetch(Reclamo.RECLAMO.FILE3, values);
	}

	/**
	 * Fetch records that have <code>file4 IN (values)</code>
	 */
	public List<matera.jooq.tables.pojos.Reclamo> fetchByFile4(byte[]... values) {
		return fetch(Reclamo.RECLAMO.FILE4, values);
	}
}
