/*
 * Derechos de uso otorgados a MyA Tecnología Quirúrgica S.A.
 * Todos los derechos reservados - 2014 -
 * BOSOFT - Servicios Inform�ticos Integrales
 * www.bosoft.com.ar
 * 
 */
package ar.com.dialogos;

import javax.swing.ImageIcon;

/**
 *
 * @author Hernán Estalella - BOSOFT Servicios Informáticos Integrales
 * <hernan_estalella@bosoft.com.ar>
 */
public class AvisoEspera extends javax.swing.JDialog {
    public static final int CARGANDO = 1;
    public static final int GUARDANDO = 2;    
    public static final int CONECTANDO = 3;    
    public static final int IMPRIMIENDO = 4;    

    /**
     * Creates new form AvisoEspera
     * @param parent
     * @param modal
     * @param opcion
     */
    public AvisoEspera(java.awt.Frame parent, boolean modal, int opcion) {
        super(parent, modal);
        initComponents();
        
        ImageIcon imagenGif = new ImageIcon(this.getClass().getResource("/recursos/gif/barra.gif"));
        ImageIcon leyenda = null;
        switch (opcion){
            case 1:
                leyenda = new ImageIcon(this.getClass().getResource("/recursos/leyendas/cargando.gif"));
                break;
            case 2:
                leyenda = new ImageIcon(this.getClass().getResource("/recursos/leyendas/guardando.gif"));
                break;
            case 3:
                leyenda = new ImageIcon(this.getClass().getResource("/recursos/leyendas/conectando.gif"));
                break;            
            case 4:
                leyenda = new ImageIcon(this.getClass().getResource("/recursos/leyendas/imprimiendo.gif"));
                break;            
                
        }
        this.leyenda.setIcon(leyenda);
        this.gif.setIcon(imagenGif);
        imagenGif.setImageObserver(this.gif);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new javax.swing.JLabel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(false);
        setUndecorated(true);
        setResizable(false);

        gif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        leyenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gif;
    private javax.swing.JLabel leyenda;
    // End of variables declaration//GEN-END:variables
}
