/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Anulaliquidacion extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1577683524;

	/**
	 * The parameter <code>matera.anulaLiquidacion.id_liquidacion</code>.
	 */
	public static final Parameter<Integer> ID_LIQUIDACION = createParameter("id_liquidacion", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.anulaLiquidacion.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Anulaliquidacion() {
		super("anulaLiquidacion", Matera.MATERA);

		addInParameter(ID_LIQUIDACION);
		addInParameter(ID_EMPRESA);
	}

	/**
	 * Set the <code>id_liquidacion</code> parameter IN value to the routine
	 */
	public void setIdLiquidacion(Integer value) {
		setValue(ID_LIQUIDACION, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}
}
