/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cambiacontraseña extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1425286901;

	/**
	 * The parameter <code>matera.cambiaContraseña.id_usuario</code>.
	 */
	public static final Parameter<Integer> ID_USUARIO = createParameter("id_usuario", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.cambiaContraseña.pass</code>.
	 */
	public static final Parameter<String> PASS = createParameter("pass", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * Create a new routine call instance
	 */
	public Cambiacontraseña() {
		super("cambiaContraseña", Matera.MATERA);

		addInParameter(ID_USUARIO);
		addInParameter(PASS);
	}

	/**
	 * Set the <code>id_usuario</code> parameter IN value to the routine
	 */
	public void setIdUsuario(Integer value) {
		setValue(ID_USUARIO, value);
	}

	/**
	 * Set the <code>pass</code> parameter IN value to the routine
	 */
	public void setPass(String value) {
		setValue(PASS, value);
	}
}
