/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consultalocalidad extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 981194406;

	/**
	 * The parameter <code>matera.consultaLocalidad.id_departamento</code>.
	 */
	public static final Parameter<Integer> ID_DEPARTAMENTO = createParameter("id_departamento", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Consultalocalidad() {
		super("consultaLocalidad", Matera.MATERA);

		addInParameter(ID_DEPARTAMENTO);
	}

	/**
	 * Set the <code>id_departamento</code> parameter IN value to the routine
	 */
	public void setIdDepartamento(Integer value) {
		setValue(ID_DEPARTAMENTO, value);
	}
}
