/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consultacajaprestada extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -852530121;

	/**
	 * The parameter <code>matera.consultaCajaPrestada.id_zonaDestino</code>.
	 */
	public static final Parameter<Integer> ID_ZONADESTINO = createParameter("id_zonaDestino", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.consultaCajaPrestada.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Consultacajaprestada() {
		super("consultaCajaPrestada", Matera.MATERA);

		addInParameter(ID_ZONADESTINO);
		addInParameter(ID_EMPRESA);
	}

	/**
	 * Set the <code>id_zonaDestino</code> parameter IN value to the routine
	 */
	public void setIdZonadestino(Integer value) {
		setValue(ID_ZONADESTINO, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}
}
