/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consultausuario extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1738397505;

	/**
	 * The parameter <code>matera.consultaUsuario.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.consultaUsuario.soloSistema</code>.
	 */
	public static final Parameter<Byte> SOLOSISTEMA = createParameter("soloSistema", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * The parameter <code>matera.consultaUsuario.soloHabilitados</code>.
	 */
	public static final Parameter<Byte> SOLOHABILITADOS = createParameter("soloHabilitados", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * Create a new routine call instance
	 */
	public Consultausuario() {
		super("consultaUsuario", Matera.MATERA);

		addInParameter(ID_EMPRESA);
		addInParameter(SOLOSISTEMA);
		addInParameter(SOLOHABILITADOS);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}

	/**
	 * Set the <code>soloSistema</code> parameter IN value to the routine
	 */
	public void setSolosistema(Byte value) {
		setValue(SOLOSISTEMA, value);
	}

	/**
	 * Set the <code>soloHabilitados</code> parameter IN value to the routine
	 */
	public void setSolohabilitados(Byte value) {
		setValue(SOLOHABILITADOS, value);
	}
}
