/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Costopesos extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = 1321076188;

	/**
	 * The parameter <code>matera.costoPesos.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 2), false);

	/**
	 * The parameter <code>matera.costoPesos.id_producto</code>.
	 */
	public static final Parameter<Integer> ID_PRODUCTO = createParameter("id_producto", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Costopesos() {
		super("costoPesos", Matera.MATERA, org.jooq.impl.SQLDataType.DECIMAL.precision(15, 2));

		setReturnParameter(RETURN_VALUE);
		addInParameter(ID_PRODUCTO);
	}

	/**
	 * Set the <code>id_producto</code> parameter IN value to the routine
	 */
	public void setIdProducto(Integer value) {
		setValue(ID_PRODUCTO, value);
	}

	/**
	 * Set the <code>id_producto</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setIdProducto(Field<Integer> field) {
		setField(ID_PRODUCTO, field);
	}
}
