/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertrevisionsoftware extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1559307693;

	/**
	 * The parameter <code>matera.insertRevisionSoftware.detalleRevision</code>.
	 */
	public static final Parameter<String> DETALLEREVISION = createParameter("detalleRevision", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * Create a new routine call instance
	 */
	public Insertrevisionsoftware() {
		super("insertRevisionSoftware", Matera.MATERA);

		addInParameter(DETALLEREVISION);
	}

	/**
	 * Set the <code>detalleRevision</code> parameter IN value to the routine
	 */
	public void setDetallerevision(String value) {
		setValue(DETALLEREVISION, value);
	}
}
