/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertfactura extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -943574688;

	/**
	 * The parameter <code>matera.insertFactura.fecha</code>.
	 */
	public static final Parameter<Date> FECHA = createParameter("fecha", org.jooq.impl.SQLDataType.DATE, false);

	/**
	 * The parameter <code>matera.insertFactura.id_presupuesto</code>.
	 */
	public static final Parameter<Integer> ID_PRESUPUESTO = createParameter("id_presupuesto", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.id_tipoComp</code>.
	 */
	public static final Parameter<Integer> ID_TIPOCOMP = createParameter("id_tipoComp", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.numComp</code>.
	 */
	public static final Parameter<String> NUMCOMP = createParameter("numComp", org.jooq.impl.SQLDataType.VARCHAR.length(12), false);

	/**
	 * The parameter <code>matera.insertFactura.id_tipoCompRel</code>.
	 */
	public static final Parameter<Integer> ID_TIPOCOMPREL = createParameter("id_tipoCompRel", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.numCompRel</code>.
	 */
	public static final Parameter<String> NUMCOMPREL = createParameter("numCompRel", org.jooq.impl.SQLDataType.VARCHAR.length(12), false);

	/**
	 * The parameter <code>matera.insertFactura.vencimiento</code>.
	 */
	public static final Parameter<Date> VENCIMIENTO = createParameter("vencimiento", org.jooq.impl.SQLDataType.DATE, false);

	/**
	 * The parameter <code>matera.insertFactura.id_formaPago</code>.
	 */
	public static final Parameter<Integer> ID_FORMAPAGO = createParameter("id_formaPago", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.dc</code>.
	 */
	public static final Parameter<String> DC = createParameter("dc", org.jooq.impl.SQLDataType.VARCHAR.length(1), false);

	/**
	 * The parameter <code>matera.insertFactura.bonificacion</code>.
	 */
	public static final Parameter<BigDecimal> BONIFICACION = createParameter("bonificacion", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.neto</code>.
	 */
	public static final Parameter<BigDecimal> NETO = createParameter("neto", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.aliPercIIBB</code>.
	 */
	public static final Parameter<BigDecimal> ALIPERCIIBB = createParameter("aliPercIIBB", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.percIIBB</code>.
	 */
	public static final Parameter<BigDecimal> PERCIIBB = createParameter("percIIBB", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.aliIva</code>.
	 */
	public static final Parameter<BigDecimal> ALIIVA = createParameter("aliIva", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.iva</code>.
	 */
	public static final Parameter<BigDecimal> IVA = createParameter("iva", org.jooq.impl.SQLDataType.DECIMAL.precision(9, 2), false);

	/**
	 * The parameter <code>matera.insertFactura.observaciones</code>.
	 */
	public static final Parameter<String> OBSERVACIONES = createParameter("observaciones", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * The parameter <code>matera.insertFactura.id_vendedor</code>.
	 */
	public static final Parameter<Integer> ID_VENDEDOR = createParameter("id_vendedor", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.comparte</code>.
	 */
	public static final Parameter<String> COMPARTE = createParameter("comparte", org.jooq.impl.SQLDataType.VARCHAR.length(1), false);

	/**
	 * The parameter <code>matera.insertFactura.id_vendedorComparte</code>.
	 */
	public static final Parameter<Integer> ID_VENDEDORCOMPARTE = createParameter("id_vendedorComparte", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertFactura.usuario</code>.
	 */
	public static final Parameter<String> USUARIO = createParameter("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * Create a new routine call instance
	 */
	public Insertfactura() {
		super("insertFactura", Matera.MATERA);

		addInParameter(FECHA);
		addInParameter(ID_PRESUPUESTO);
		addInParameter(ID_TIPOCOMP);
		addInParameter(NUMCOMP);
		addInParameter(ID_TIPOCOMPREL);
		addInParameter(NUMCOMPREL);
		addInParameter(VENCIMIENTO);
		addInParameter(ID_FORMAPAGO);
		addInParameter(DC);
		addInParameter(BONIFICACION);
		addInParameter(NETO);
		addInParameter(ALIPERCIIBB);
		addInParameter(PERCIIBB);
		addInParameter(ALIIVA);
		addInParameter(IVA);
		addInParameter(OBSERVACIONES);
		addInParameter(ID_VENDEDOR);
		addInParameter(COMPARTE);
		addInParameter(ID_VENDEDORCOMPARTE);
		addInParameter(ID_EMPRESA);
		addInParameter(USUARIO);
	}

	/**
	 * Set the <code>fecha</code> parameter IN value to the routine
	 */
	public void setFecha(Date value) {
		setValue(FECHA, value);
	}

	/**
	 * Set the <code>id_presupuesto</code> parameter IN value to the routine
	 */
	public void setIdPresupuesto(Integer value) {
		setValue(ID_PRESUPUESTO, value);
	}

	/**
	 * Set the <code>id_tipoComp</code> parameter IN value to the routine
	 */
	public void setIdTipocomp(Integer value) {
		setValue(ID_TIPOCOMP, value);
	}

	/**
	 * Set the <code>numComp</code> parameter IN value to the routine
	 */
	public void setNumcomp(String value) {
		setValue(NUMCOMP, value);
	}

	/**
	 * Set the <code>id_tipoCompRel</code> parameter IN value to the routine
	 */
	public void setIdTipocomprel(Integer value) {
		setValue(ID_TIPOCOMPREL, value);
	}

	/**
	 * Set the <code>numCompRel</code> parameter IN value to the routine
	 */
	public void setNumcomprel(String value) {
		setValue(NUMCOMPREL, value);
	}

	/**
	 * Set the <code>vencimiento</code> parameter IN value to the routine
	 */
	public void setVencimiento(Date value) {
		setValue(VENCIMIENTO, value);
	}

	/**
	 * Set the <code>id_formaPago</code> parameter IN value to the routine
	 */
	public void setIdFormapago(Integer value) {
		setValue(ID_FORMAPAGO, value);
	}

	/**
	 * Set the <code>dc</code> parameter IN value to the routine
	 */
	public void setDc(String value) {
		setValue(DC, value);
	}

	/**
	 * Set the <code>bonificacion</code> parameter IN value to the routine
	 */
	public void setBonificacion(BigDecimal value) {
		setValue(BONIFICACION, value);
	}

	/**
	 * Set the <code>neto</code> parameter IN value to the routine
	 */
	public void setNeto(BigDecimal value) {
		setValue(NETO, value);
	}

	/**
	 * Set the <code>aliPercIIBB</code> parameter IN value to the routine
	 */
	public void setAliperciibb(BigDecimal value) {
		setValue(ALIPERCIIBB, value);
	}

	/**
	 * Set the <code>percIIBB</code> parameter IN value to the routine
	 */
	public void setPerciibb(BigDecimal value) {
		setValue(PERCIIBB, value);
	}

	/**
	 * Set the <code>aliIva</code> parameter IN value to the routine
	 */
	public void setAliiva(BigDecimal value) {
		setValue(ALIIVA, value);
	}

	/**
	 * Set the <code>iva</code> parameter IN value to the routine
	 */
	public void setIva(BigDecimal value) {
		setValue(IVA, value);
	}

	/**
	 * Set the <code>observaciones</code> parameter IN value to the routine
	 */
	public void setObservaciones(String value) {
		setValue(OBSERVACIONES, value);
	}

	/**
	 * Set the <code>id_vendedor</code> parameter IN value to the routine
	 */
	public void setIdVendedor(Integer value) {
		setValue(ID_VENDEDOR, value);
	}

	/**
	 * Set the <code>comparte</code> parameter IN value to the routine
	 */
	public void setComparte(String value) {
		setValue(COMPARTE, value);
	}

	/**
	 * Set the <code>id_vendedorComparte</code> parameter IN value to the routine
	 */
	public void setIdVendedorcomparte(Integer value) {
		setValue(ID_VENDEDORCOMPARTE, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}

	/**
	 * Set the <code>usuario</code> parameter IN value to the routine
	 */
	public void setUsuario(String value) {
		setValue(USUARIO, value);
	}
}
