/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertintersucursalcaja extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 986874706;

	/**
	 * The parameter <code>matera.insertIntersucursalCaja.id_cajaDeposito</code>.
	 */
	public static final Parameter<Integer> ID_CAJADEPOSITO = createParameter("id_cajaDeposito", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertIntersucursalCaja.devuelto</code>.
	 */
	public static final Parameter<String> DEVUELTO = createParameter("devuelto", org.jooq.impl.SQLDataType.VARCHAR.length(1), false);

	/**
	 * Create a new routine call instance
	 */
	public Insertintersucursalcaja() {
		super("insertIntersucursalCaja", Matera.MATERA);

		addInParameter(ID_CAJADEPOSITO);
		addInParameter(DEVUELTO);
	}

	/**
	 * Set the <code>id_cajaDeposito</code> parameter IN value to the routine
	 */
	public void setIdCajadeposito(Integer value) {
		setValue(ID_CAJADEPOSITO, value);
	}

	/**
	 * Set the <code>devuelto</code> parameter IN value to the routine
	 */
	public void setDevuelto(String value) {
		setValue(DEVUELTO, value);
	}
}
