/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertforecast extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1022292316;

	/**
	 * The parameter <code>matera.insertForecast.anio</code>.
	 */
	public static final Parameter<Integer> ANIO = createParameter("anio", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecast.id_vendedor</code>.
	 */
	public static final Parameter<Integer> ID_VENDEDOR = createParameter("id_vendedor", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecast.id_entidad</code>.
	 */
	public static final Parameter<Integer> ID_ENTIDAD = createParameter("id_entidad", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecast.id_productoFact</code>.
	 */
	public static final Parameter<Integer> ID_PRODUCTOFACT = createParameter("id_productoFact", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecast.cantidad</code>.
	 */
	public static final Parameter<Double> CANTIDAD = createParameter("cantidad", org.jooq.impl.SQLDataType.DOUBLE, false);

	/**
	 * The parameter <code>matera.insertForecast.usuario</code>.
	 */
	public static final Parameter<String> USUARIO = createParameter("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * Create a new routine call instance
	 */
	public Insertforecast() {
		super("insertForecast", Matera.MATERA);

		addInParameter(ANIO);
		addInParameter(ID_VENDEDOR);
		addInParameter(ID_ENTIDAD);
		addInParameter(ID_PRODUCTOFACT);
		addInParameter(CANTIDAD);
		addInParameter(USUARIO);
	}

	/**
	 * Set the <code>anio</code> parameter IN value to the routine
	 */
	public void setAnio(Integer value) {
		setValue(ANIO, value);
	}

	/**
	 * Set the <code>id_vendedor</code> parameter IN value to the routine
	 */
	public void setIdVendedor(Integer value) {
		setValue(ID_VENDEDOR, value);
	}

	/**
	 * Set the <code>id_entidad</code> parameter IN value to the routine
	 */
	public void setIdEntidad(Integer value) {
		setValue(ID_ENTIDAD, value);
	}

	/**
	 * Set the <code>id_productoFact</code> parameter IN value to the routine
	 */
	public void setIdProductofact(Integer value) {
		setValue(ID_PRODUCTOFACT, value);
	}

	/**
	 * Set the <code>cantidad</code> parameter IN value to the routine
	 */
	public void setCantidad(Double value) {
		setValue(CANTIDAD, value);
	}

	/**
	 * Set the <code>usuario</code> parameter IN value to the routine
	 */
	public void setUsuario(String value) {
		setValue(USUARIO, value);
	}
}
