/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertmayortecnico extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1568694821;

	/**
	 * The parameter <code>matera.insertMayorTecnico.fecha</code>.
	 */
	public static final Parameter<Date> FECHA = createParameter("fecha", org.jooq.impl.SQLDataType.DATE, false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.id_presupuesto</code>.
	 */
	public static final Parameter<Integer> ID_PRESUPUESTO = createParameter("id_presupuesto", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.id_tecnico</code>.
	 */
	public static final Parameter<Integer> ID_TECNICO = createParameter("id_tecnico", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.dc</code>.
	 */
	public static final Parameter<String> DC = createParameter("dc", org.jooq.impl.SQLDataType.VARCHAR.length(1), false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.importe</code>.
	 */
	public static final Parameter<BigDecimal> IMPORTE = createParameter("importe", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2), false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.observaciones</code>.
	 */
	public static final Parameter<String> OBSERVACIONES = createParameter("observaciones", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertMayorTecnico.usuario</code>.
	 */
	public static final Parameter<String> USUARIO = createParameter("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * Create a new routine call instance
	 */
	public Insertmayortecnico() {
		super("insertMayorTecnico", Matera.MATERA);

		addInParameter(FECHA);
		addInParameter(ID_PRESUPUESTO);
		addInParameter(ID_TECNICO);
		addInParameter(DC);
		addInParameter(IMPORTE);
		addInParameter(OBSERVACIONES);
		addInParameter(ID_EMPRESA);
		addInParameter(USUARIO);
	}

	/**
	 * Set the <code>fecha</code> parameter IN value to the routine
	 */
	public void setFecha(Date value) {
		setValue(FECHA, value);
	}

	/**
	 * Set the <code>id_presupuesto</code> parameter IN value to the routine
	 */
	public void setIdPresupuesto(Integer value) {
		setValue(ID_PRESUPUESTO, value);
	}

	/**
	 * Set the <code>id_tecnico</code> parameter IN value to the routine
	 */
	public void setIdTecnico(Integer value) {
		setValue(ID_TECNICO, value);
	}

	/**
	 * Set the <code>dc</code> parameter IN value to the routine
	 */
	public void setDc(String value) {
		setValue(DC, value);
	}

	/**
	 * Set the <code>importe</code> parameter IN value to the routine
	 */
	public void setImporte(BigDecimal value) {
		setValue(IMPORTE, value);
	}

	/**
	 * Set the <code>observaciones</code> parameter IN value to the routine
	 */
	public void setObservaciones(String value) {
		setValue(OBSERVACIONES, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}

	/**
	 * Set the <code>usuario</code> parameter IN value to the routine
	 */
	public void setUsuario(String value) {
		setValue(USUARIO, value);
	}
}
