/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import java.sql.Date;

import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertajustestockdetalle extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 584181035;

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.id_producto</code>.
	 */
	public static final Parameter<Integer> ID_PRODUCTO = createParameter("id_producto", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.cantidad</code>.
	 */
	public static final Parameter<Integer> CANTIDAD = createParameter("cantidad", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.dc</code>.
	 */
	public static final Parameter<String> DC = createParameter("dc", org.jooq.impl.SQLDataType.VARCHAR.length(1), false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.lote</code>.
	 */
	public static final Parameter<String> LOTE = createParameter("lote", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.serie</code>.
	 */
	public static final Parameter<String> SERIE = createParameter("serie", org.jooq.impl.SQLDataType.VARCHAR.length(255), false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.pm</code>.
	 */
	public static final Parameter<String> PM = createParameter("pm", org.jooq.impl.SQLDataType.VARCHAR.length(45), false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.vencimiento</code>.
	 */
	public static final Parameter<Date> VENCIMIENTO = createParameter("vencimiento", org.jooq.impl.SQLDataType.DATE, false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.observaciones</code>.
	 */
	public static final Parameter<String> OBSERVACIONES = createParameter("observaciones", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.id_zona</code>.
	 */
	public static final Parameter<Integer> ID_ZONA = createParameter("id_zona", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertAjusteStockDetalle.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Insertajustestockdetalle() {
		super("insertAjusteStockDetalle", Matera.MATERA);

		addInParameter(ID_PRODUCTO);
		addInParameter(CANTIDAD);
		addInParameter(DC);
		addInParameter(LOTE);
		addInParameter(SERIE);
		addInParameter(PM);
		addInParameter(VENCIMIENTO);
		addInParameter(OBSERVACIONES);
		addInParameter(ID_ZONA);
		addInParameter(ID_EMPRESA);
	}

	/**
	 * Set the <code>id_producto</code> parameter IN value to the routine
	 */
	public void setIdProducto(Integer value) {
		setValue(ID_PRODUCTO, value);
	}

	/**
	 * Set the <code>cantidad</code> parameter IN value to the routine
	 */
	public void setCantidad(Integer value) {
		setValue(CANTIDAD, value);
	}

	/**
	 * Set the <code>dc</code> parameter IN value to the routine
	 */
	public void setDc(String value) {
		setValue(DC, value);
	}

	/**
	 * Set the <code>lote</code> parameter IN value to the routine
	 */
	public void setLote(String value) {
		setValue(LOTE, value);
	}

	/**
	 * Set the <code>serie</code> parameter IN value to the routine
	 */
	public void setSerie(String value) {
		setValue(SERIE, value);
	}

	/**
	 * Set the <code>pm</code> parameter IN value to the routine
	 */
	public void setPm(String value) {
		setValue(PM, value);
	}

	/**
	 * Set the <code>vencimiento</code> parameter IN value to the routine
	 */
	public void setVencimiento(Date value) {
		setValue(VENCIMIENTO, value);
	}

	/**
	 * Set the <code>observaciones</code> parameter IN value to the routine
	 */
	public void setObservaciones(String value) {
		setValue(OBSERVACIONES, value);
	}

	/**
	 * Set the <code>id_zona</code> parameter IN value to the routine
	 */
	public void setIdZona(Integer value) {
		setValue(ID_ZONA, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}
}
