/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Insertforecastcomposiciongrupo extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -365056485;

	/**
	 * The parameter <code>matera.insertForecastComposicionGrupo.id_forecastGrupo</code>.
	 */
	public static final Parameter<Integer> ID_FORECASTGRUPO = createParameter("id_forecastGrupo", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecastComposicionGrupo.id_productoFact</code>.
	 */
	public static final Parameter<Integer> ID_PRODUCTOFACT = createParameter("id_productoFact", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.insertForecastComposicionGrupo.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Insertforecastcomposiciongrupo() {
		super("insertForecastComposicionGrupo", Matera.MATERA);

		addInParameter(ID_FORECASTGRUPO);
		addInParameter(ID_PRODUCTOFACT);
		addInParameter(ID_EMPRESA);
	}

	/**
	 * Set the <code>id_forecastGrupo</code> parameter IN value to the routine
	 */
	public void setIdForecastgrupo(Integer value) {
		setValue(ID_FORECASTGRUPO, value);
	}

	/**
	 * Set the <code>id_productoFact</code> parameter IN value to the routine
	 */
	public void setIdProductofact(Integer value) {
		setValue(ID_PRODUCTOFACT, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}
}
