/**
 * This class is generated by jOOQ
 */
package matera.jooq.routines;


import javax.annotation.Generated;

import matera.jooq.Matera;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Traealtastock extends AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1552238631;

	/**
	 * The parameter <code>matera.traeAltaStock.id_stock</code>.
	 */
	public static final Parameter<Integer> ID_STOCK = createParameter("id_stock", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>matera.traeAltaStock.id_empresa</code>.
	 */
	public static final Parameter<Integer> ID_EMPRESA = createParameter("id_empresa", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public Traealtastock() {
		super("traeAltaStock", Matera.MATERA);

		addInParameter(ID_STOCK);
		addInParameter(ID_EMPRESA);
	}

	/**
	 * Set the <code>id_stock</code> parameter IN value to the routine
	 */
	public void setIdStock(Integer value) {
		setValue(ID_STOCK, value);
	}

	/**
	 * Set the <code>id_empresa</code> parameter IN value to the routine
	 */
	public void setIdEmpresa(Integer value) {
		setValue(ID_EMPRESA, value);
	}
}
